### ISSUE TITLE
Remove "New" label on posts for the author - DCE 356

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#10]
How to reproduce:

1. Open any post
2. Comment or answer
3. Go to main page
4. The post that you commented or answered now has a "New" label. it shouldn't.

![image](https://user-images.githubusercontent.com/5127457/36374905-139fa25a-157e-11e8-8a19-71c009bce340.png)

**Comment by lelikone** [comment]
couldn't reproduce the problem

**Comment by evshvarov** [comment]
Fixed
