### ISSUE TITLE
Add Ban Member option for moderators

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/developer-community#101]
A banned member will not be able to contribute to the site.

The UI
Mods will see for any [member](https://community.intersystems.com/user/manchun-kumar) the status:
Status: active/banned.
If the status is "active" then the action "Ban a Member" will be available for mods. It will have a dropdown with "week, month, forever"

If the status is "banned" it shows also "banned until "date" by "moderator" date of the action.
And the action "Release banning".
The action will turn member's status into Active and will result in the comment, who released the ban and when for "Active status".

**Comment by evshvarov** [comment]
> Band

We'll  decide it on our own

**Comment by eduard93** [comment]
Please change "Banned for .." label to "Ban for ..."

**Comment by evshvarov** [comment]
> When would we know how to Release the Band?

Hi @Noggin79s ! Monthly and weekly bans will release automatically. And moderator can release member of any type of ban. Also all the mods will see who released the ban from a person.

**Comment by evshvarov** [comment]
Done
