### ISSUE TITLE
Markdown tables look bad and no way to make it better

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#103]
Here's a markdown table:

```
| Method       | Callout | System | Java    | Node     |
|--------------|---------|--------|---------|----------|
| Time         | 22,77   | 33,41  | 152,73  | 622,51   |
| Speed (Kb/s) | 43912   | 29927  | 6547    | 1606     |
| Overhead, %  | -/-     | 46,73% | 570,75% | 2633,90% |
```

Here's how GitHub renders it:
![image](https://user-images.githubusercontent.com/5127457/50541180-394d6080-0bb1-11e9-87ef-9a519e7ef858.png)

And here's how we render it:
![image](https://user-images.githubusercontent.com/5127457/50541181-4b2f0380-0bb1-11e9-9918-7612efc282af.png)

We need to render markdown tables better (and WYSWIG tables too actually). 
Let's change default table style to add spacings and borders.

**Comment by lelikone** [comment]
@eduard93 

Hello, Eduard. 
Check to see if I have made a table showing?
You can do this in a draft.
I attach a screenshot of the table now.

![image](https://user-images.githubusercontent.com/21163767/62409107-475ed600-b605-11e9-81e3-6bff4930b652.png)

**Comment by eduard93** [comment]
Looks good!

**Comment by evshvarov** [comment]
@eduard93 is it fixed?

**Comment by evshvarov** [comment]
@eduard93
