### ISSUE TITLE
Do not send mod mail about mod actions on own posts

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#104]
I received an email about my deleted draft.
Moderator should be able to delete his own posts/comments/drafts/answers without mod mail being sent to everyone.

**Comment by evshvarov** [comment]
Hi @eduard93 , could you please check if this is solved?

**Comment by eduard93** [comment]
Checking. Performed draft delete. Would close in a few days if I would receive no notifications.

**Comment by evshvarov** [comment]
@eduard93 could you please close an issue?
