### ISSUE TITLE
Inline single quotes in markdown editor should produce code formatting

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#105]
Currently inline single quotes produce different formatting from quotes-on-a-separate-line. 

![image](https://user-images.githubusercontent.com/5127457/50541816-b0d5bc80-0bbe-11e9-9599-9cec344d6136.png)

However, inline quotes should produce `this code effect`

**Comment by lelikone** [comment]
@eduard93 Hello, Eduard. Can you describe the problem in more detail?  Give us a code sample, and what's wrong with it?

**Comment by eduard93** [comment]
Text:
![image](https://user-images.githubusercontent.com/5127457/63874804-db387d80-c9ca-11e9-9766-7c900d4a3889.png)

Incorrect render:
![image](https://user-images.githubusercontent.com/5127457/63874826-e7bcd600-c9ca-11e9-9e54-6caee594d408.png)

**Comment by lelikone** [comment]
Hello: `code`

```
Code 2
```

**Comment by lelikone** [comment]
@eduard93 
Hello, Eduard. I have studied the markdown documentation. The processing is correct, for example, see the message above. GIT also processes the data.

**Comment by lelikone** [comment]
![image](https://user-images.githubusercontent.com/21163767/66289530-88c67700-e90f-11e9-855a-56f210fab7c9.png)
Use backslash

**Comment by eduard93** [comment]
It shouldn't be red

**Comment by eduard93** [comment]
It should be formatted `like this`

**Comment by lelikone** [comment]
@eduard93 
Check now. If all is well, you can close the task.

**Comment by eduard93** [comment]
Yes!
