### ISSUE TITLE
Extended Notification about changes in post done by Moderators 

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#112]
We now have email notification to the post's author when any moderator changed it.
But It would be better if this email will contain the Name of a moderator, and if possible, a list of changes which was done, or maybe some comment from a moderator about changes.

**Comment by lelikone** [comment]
email will contain the Name of a moderator

**Comment by eduard93** [comment]
What changed would be great

**Comment by eduard93** [comment]
Closed accidentally.

**Comment by evshvarov** [comment]
@daimor , @eduard93 - check the changes please?

**Comment by evshvarov** [comment]
@daimor close please?

**Comment by evshvarov** [comment]
@daimor up )
