### ISSUE TITLE
Give moderators a way of finding who's banned, or who's on moderation

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#113]

**Comment by evshvarov** [comment]
Status of a member is available on every member's page. Possible statuses: Trusted, On Moderation, Banned.
@gjsjohnmurray, could you please check if we can close the issue?

**Comment by evshvarov** [comment]
I think it makes sense to add three new filters on Members page visible only to Mods: Trusted, On Moderation, Banned with Totals for every category

**Comment by gjsjohnmurray** [comment]
Status is visible to me on a member's page. I agree that filters would be useful.

**Comment by evshvarov** [comment]
@gjsjohnmurray , could we close the issue?

**Comment by gjsjohnmurray** [comment]
Done!
