### ISSUE TITLE
Search finds a comment but the link doesn't locate it

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#12]
Try searching for "schema upgrade" (without quotes). The first result is a comment I posted on 15 March 2016. The result page shows the start of the comment, which begins "That's certainly a useful tip. I wonder if it would have helped in a situation we assisted an Ensemble site with last year." 

Bbut when I follow the hyperlinked "Comment:" header to https://community.intersystems.com/post/managing-source-code-across-cach%C3%A9-and-ensemble-version-upgrades#comment-6401 I don't see my comment. I only see one comment, and that's by someone else.

**Comment by evshvarov** [comment]
Wow. Lost comment? That looks like a serious bug.

**Comment by lelikone** [comment]
In the example, no words from the query. Here is the error because of an incorrect search. Invalid search returned invalid result links.

**Comment by lelikone** [comment]
An error occurs if the database is preserved comments for deleted posts

**Comment by evshvarov** [comment]
Fixed

**Comment by evshvarov** [comment]
Please, check if it works well

**Comment by gjsjohnmurray** [comment]
Now works correctly on the example I originally gave.
