### ISSUE TITLE
Make 10 lines as a minimum for teaser on main and don't cut the words

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/developer-community#127]
Sometimes we just see 
"Hi Community!" 
on main. 
E.g. for this one(https://community.intersystems.com/post/accessing-lock-table-and-another-processs-variables-potentially-different-server)
<img width="939" alt="screenshot 2019-02-15 15 27 34" src="https://user-images.githubusercontent.com/2781759/52882612-40670880-3136-11e9-8c60-5d57dada7633.png">

Let's show first 10 lines and then break it.

**Comment by lelikone** [comment]
@evshvarov  maybe it's better to use five lines for teaser?

**Comment by evshvarov** [comment]
5 is definitely better than 1 now. OK

**Comment by eduard93** [comment]
Five lines of what? Source html? Displayed html? 
How are we calculating it?
