### ISSUE TITLE
Current input type overrrides post input type

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#13]
Caused by: #8

How to reproduce:

1. Write and publish post in MD.
2. Write and publish post in WYSWIG
3. Open post 1 for edit.

Expected behavior: Post opens for edit in MD
Actual behavior: Post opens for edit in WYSWIG. Post is uneditable. All formatting is lost on save.

Proposed solution: open post for edit in it's last edit format.
Current workaround: create draft in MD and save it (or publish comment/answer in MD).  Open MD post from 1 for edit. It would open in MD.

Further notes: Same goes for answers/comments.

**Comment by evshvarov** [comment]
This happens because of that: https://github.com/intersystems-community/developer-community/issues/8

**Comment by evshvarov** [comment]
It remembers the last took editor

**Comment by lelikone** [comment]
This problem is solved
