### ISSUE TITLE
Deleted Answers still showing up

### ISSUE THREAD

**Issue by Noggin79s** [intersystems-community/developer-community#131]
Accidentally went to put a comment on the following thread and then deleted it. However it is still showing my question answered which it isn't.

https://community.intersystems.com/post/hl7-orur40-schema-structure

**Comment by Noggin79s** [comment]
![image](https://user-images.githubusercontent.com/29753377/53182109-d8497400-35c6-11e9-9a61-25fb022d05ee.png)

**Comment by evshvarov** [comment]
@Noggin79s , could you please check if this is solved?

**Comment by Noggin79s** [comment]
Go ahead and close the issue. Thanks
