### ISSUE TITLE
Convert comment to question

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#135]

**Comment by lelikone** [comment]
@daimor 
Hi, Dmitry.
I made this opportunity. Now each comment has an icon to convert the comment into a question. Available only for moderators.
![image](https://user-images.githubusercontent.com/21163767/84509444-48b56080-acf6-11ea-807b-7625163c8c39.png)

**Comment by evshvarov** [comment]
@daimor , can we close it?
