### ISSUE TITLE
Markdown preview is broken

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#139]
[Article in markdown](https://community.intersystems.com/post/ensemble-rabbitmq-java-client-quick-start-guide)

Preview looks like this:
![image](https://user-images.githubusercontent.com/5127457/53788820-e5098880-3f33-11e9-9856-a63f005eba55.png)

**Comment by lelikone** [comment]
I see fine
![image](https://user-images.githubusercontent.com/21163767/53789673-f5375d00-3f5f-11e9-957f-e47f56f7df69.png)

**Comment by eduard93** [comment]
The article is fine. I'm talking about preview on a main page:
![image](https://user-images.githubusercontent.com/5127457/53789952-c3f66700-3f36-11e9-80af-8ee7dc0a4b66.png)

**Comment by eduard93** [comment]
[Relevant])https://github.com/intersystems-community/developer-community/issues/127)?

**Comment by lelikone** [comment]
Previously, only 1 sentence was used in the preview. And so it was not visible this problem. Now we use a few sentences. And the Preview shows the rest of the information. It is 127  issue

**Comment by evshvarov** [comment]
@eduard93 , is it solved? Close please?

**Comment by eduard93** [comment]
Looks like preview works now
![image](https://user-images.githubusercontent.com/5127457/56133177-7b4db700-5f94-11e9-94de-4ffd91ddc469.png)
