### ISSUE TITLE
Add Bookmarks or Favorites

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#14]
Add for user an option to bookmark or favorite:

- posts
- answers
- comments

And to view bookmarks/favorites from user's account.

**Comment by eduard93** [comment]
I see bookmarks on posts, but not on answers or comments.

**Comment by evshvarov** [comment]
@eduard93, could you please close if it works for you?

**Comment by eduard93** [comment]
Bookmarks for posts and comments are not available.

**Comment by evshvarov** [comment]
I think it is a very different feature.
Let's introduce it as a new task and decide how to do it

**Comment by eduard93** [comment]
Closed with https://github.com/intersystems-community/developer-community/issues/32
