### ISSUE TITLE
Private messaging between DC members

### ISSUE THREAD

**Issue by mdavidovich85** [intersystems-community/developer-community#142]
This may go against the spirit of a forum like the DC, but it would be helpful if DC members who wanted to connect 1:1 to discuss very specific issues or wanted to be personal contacts, it would be helpful to have a way to either message each other directly or share contact information privately.

**Comment by evshvarov** [comment]
We could introduce as a contact information share. E.g. if you want to contact directly a person you click his profile which will send him standard notification from the system that "Someone with someone@email.com wants to contact you via email"
Would it work?

**Comment by rstaylor** [comment]
I think this would be quite useful.  I like the control you suggest so you don't get spammed continually.  We would need the ability to rescind that permission too.

**Comment by mdavidovich85** [comment]
Unless you can build in a private messaging system (e.g. LinkedIn, Facebook), I think what you explain makes sense and is a good option.  

I don't know how complex or easy it is to replicate what CraigsList.com does where you email an "encrypted" address and if the person replies they then expose their actual email address.  I quote encrypted because I'm not actually sure it's encrypted, but it does give a layer of privacy and security.  This allows us to skip a standard message and let the person contact them directly.  The person contacted can determine if they want to reply based on the actual message rather than the generic system message.

Even though I suggested this, if I can get philosophical for a moment: it may be a larger conversation if this feature should be added.  The spirit of the DC, I assume, is open conversation and collaboration.    Instead of people solving problems publicly, when they find a person they think can help them solve their problem, they may end up solving it privately and never reporting back to the DC.  On the other hand, sharing contact information would be a really helpful way to build your professional network.  

Double edged sword!

**Comment by leodec11** [comment]
It will be helpful if direct contact detail available.. but i still appreciate if the correct answer submitted on forum as well... it will help lot of people...

**Comment by mdavidovich85** [comment]
Another issue I just ran into where this option could cause problems: someone reached out to me on LinkedIn who had saw a post of mine.  He was trying to sell me services and products as a result, instead of participating in this 'open source idea sharing' of the DC.  I don't know if there are hard and fast rules around this, but it seems a requirement of any private message feature is that the user shall be able to block or ignore at any time.

**Comment by evshvarov** [comment]
Hi @mdavidovich85 ! We introduced the support of [Github and LinkedIn](https://github.com/intersystems-community/developer-community/issues/145) profiles on members' page.
I think this could be considered a step forward to simplify PM communication between members?
