### ISSUE TITLE
Temporarily Unavailable when viewing my own answers, posts, comments

### ISSUE THREAD

**Issue by adaptun** [intersystems-community/developer-community#159]
I cannot view my answers when I logged-in. This started at least month ago.

Opening this page:
https://community.intersystems.com/user/9906/answers

I get:
Temporarily Unavailable
The website that you're trying to reach is having technical difficulties and is currently unavailable.
We are aware of the issue and are working hard to fix it. Thank you for your patience.

If I open the same page without logging-in I see it OK.

The same with posts, comments, badges

**Comment by lelikone** [comment]
@adaptun Проверьте сейчас, проявляется эта ошибка или нет?

**Comment by adaptun** [comment]
@lelikone No! Working fine now. Thanks!

**Comment by jorge-delagarza** [comment]
I am now seeing this issue as well, for example with the following URL:
https://community.intersystems.com/user/42282/posts

When I am logged in, I get the same error message described above.  When I'm not logged in, though, I am able to access the above URL.

**Comment by lelikone** [comment]
@jorge-delagarza  Check now if this error is showing up or not?

**Comment by evshvarov** [comment]
is it fixed?

**Comment by evshvarov** [comment]
@adaptun, could we close this?

**Comment by evshvarov** [comment]
@adaptun up )

**Comment by adaptun** [comment]
works ok. thank you!
