### ISSUE TITLE
Converting a Question to an Article hides certain responses

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#16]
Suppose I post a Question. Over time, other DC members respond with Answers, or add Comments to my original Question. Then other DC members add Comments to the posted Answers.

Later I decide that my post is better treated as an Article rather than a Question. So I edit it and change its type.

Thereafter, only the Comments made on my original post remain visible. All the Answers vanish, along with Comments made to those Answers, and Comments on those Comments.

I think the Answers and their Comments should instead be converted to Comments on my Article.

Luckily I can recover the lost Answers and their Comments by resetting the post to be a Question.

**Comment by evshvarov** [comment]
I think, we better add an option to convert Comment to Answer and vice/versa. Just not to convert dozen answers to comments by mistake and than trying to understand which is answer or comment if we want the back conversion from article to question.

**Comment by rcemper** [comment]
I like the idea of Comment<==>Answer conversion.
So the conversion Question  ==> Article is real work.  
And it should be blocked with existing Answers not converted to Comment

**Comment by evshvarov** [comment]
@gjsjohnmurray we've introduced #31 recently.
Maybe it solves this issue too?

**Comment by gjsjohnmurray** [comment]
@evshvarov maybe the #31 dev could verify that? I hope my description of this issue is clear enough.

**Comment by gjsjohnmurray** [comment]
DC still allowed me (as author? or as mod?) to change a post I originally made as a Question and turn it into an Article. The 2 answers on the post disappeared. So I turned it back to a Question, converted the Answers to Comments, then turned the post into an Article. But if I hadn't been paying attention, the two Answers could have been lost. If DC isn't going to auto-convert the Answers to Comments then I like Robert's suggestion above about blocking the Question->Article (or Question->Announcement) change when any Answers exist.

**Comment by gjsjohnmurray** [comment]
Not so much an experiment as an actual case of a post that doesn't really have one "correct" answer. So I think it's better as an Article. I didn't intend it to get promoted to the top of the list.

**Comment by rcemper** [comment]
I fully support this principle.
I've also seen quite a number of questions that have no REAL Answer:
I like this,

**Comment by evshvarov** [comment]
OK! Let's introduce the task to block Question to Article conversion for questions which have any answers. Simple answers could be converted to comments if the question is needed to be converted.
If the article has an accepted answer the conversion is impossible

**Comment by evshvarov** [comment]
I think we could fix it if we convert all answers to Comments and name Comments to Replies.
With the feature of having an Accepted Reply as an Accepted answer. 
What do you think @gjsjohnmurray ?

**Comment by gjsjohnmurray** [comment]
@evshvarov sounds like a good plan.

**Comment by rcemper** [comment]
That's a fine solution:   
.Answers => Comments
.CommentToAnswer => CommentToComment  
BINGO

**Comment by evshvarov** [comment]
This is solved now, I believe. @gjsjohnmurray , close please?
