### ISSUE TITLE
Typo in translation notification email

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#167]
![image](https://user-images.githubusercontent.com/6726799/56646223-0dca1680-6677-11e9-82b0-afb456ab6d32.png)

**Comment by evshvarov** [comment]
This is done, I hope? @gjsjohnmurray ?

**Comment by gjsjohnmurray** [comment]
I don't think I've had any of my articles translated recently, so can't confirm. But am closing it anyway.
