### ISSUE TITLE
Top posts list, show post's group

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#18]
I think it needs mostly for moderators. I want to see which group was used to place post just from the list of all posts, as we already can see tags. So, it will be possible to quickly find wrong ones and fix them. Currently, group visible only when open post.

**Comment by evshvarov** [comment]
Maybe we will change the concept of groups. 
Today only one group is allowed for the post, which very inconvenient, if you try to find say all posts for Caché. 
It would be easier if we stay only with tags and use tag pages as group pages are being used now. What do you think?

**Comment by evshvarov** [comment]
I think we have it, right? Closing @daimor ?
