### ISSUE TITLE
No accepted answer does not show newest first

### ISSUE THREAD

**Issue by adaptun** [intersystems-community/developer-community#184]
Choosing "No accepted answer" on main page:
https://community.intersystems.com/?filter=unanswered

First questions shown are two years-three old and recent ones are not shown.

I expect questions to be sorted by "Updatedate desc". As when choosing "No answer"

**Comment by adaptun** [comment]
With new interface if I choose Posts: "No accepted answer", Period: "Last Month", the no posts are shown.
![Screenshot 2019-06-27 at 15 58 59](https://user-images.githubusercontent.com/1929255/60268181-7e4e1780-98f4-11e9-8cb5-6aa3865aea36.png)

**Comment by lelikone** [comment]
@adaptun that's right. The questions that were created in the past month have accepted answer.

**Comment by adaptun** [comment]
> @adaptun that's right. The questions that were created in the past month have accepted answer.

No, on main page there are several questions without accepted answer created in last month

**Comment by adaptun** [comment]
For example

https://community.intersystems.com/post/detecting-how-many-parameters-were-passed-function

https://community.intersystems.com/post/cache-ensemble

**Comment by lelikone** [comment]
@adaptun 
Use period "This month"

https://community.intersystems.com/?filter=unanswered&period=month

![image](https://user-images.githubusercontent.com/21163767/60273231-3b0d9c00-9928-11e9-8c08-ca1b5be38fa2.png)

**Comment by adaptun** [comment]
@lelikone cool, thanks!
