### ISSUE TITLE
Change translation

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#187]
Please change these translations on the Spanish version of the DC:
* Publicaciones instead of Envíos
* Todas instead of Todo(s)
* Nuevas instead of Nuevo
* Sin respuesta aceptada instead of Ninguna respuesta aceptada
* Contacto instead of Contáctenos
* Reportar incidencias instead of Report an issue

**Comment by evshvarov** [comment]
Hi @CM-DC-ES !
Thanks for submitting the issue! If you could provide a screenshot It' would be easier for the developer to find the place to fix. thanks!

**Comment by CM-DC-ES** [comment]
![Captura de pantalla 2019-05-21 a las 12 21 39](https://user-images.githubusercontent.com/50864675/58088489-14d73c80-7bc3-11e9-9b04-76b58ab6de76.png)
![Captura de pantalla 2019-05-21 a las 12 23 51](https://user-images.githubusercontent.com/50864675/58088601-536cf700-7bc3-11e9-96e0-80d702d2ad64.png)

**Comment by lelikone** [comment]
fix

**Comment by evshvarov** [comment]
@CM-DC-ES is it fixed?

**Comment by CM-DC-ES** [comment]
Hi! Yes, it is fixed. Do I have to do something?
Thanks!
Esther

**Comment by evshvarov** [comment]
thanks, @CM-DC-ES !
