### ISSUE TITLE
If translate from spanish to english, the translate tab doesn't display the link

### ISSUE THREAD

**Issue by KurroLopez** [intersystems-community/developer-community#191]
If a translate has been done from spanish community to english, there is a link between english and spanish, however the spanish tab displays a button to request a translate. 

I've recived a notifiaction to transalte a post that I've posted and translate. I've seen the button to ask translate.

**Spanish Community**
![SpanishCommunity](https://user-images.githubusercontent.com/40236469/58232342-98b33500-7d39-11e9-8c57-53b55393febb.png)

**English Community**
![EnglishCommunity](https://user-images.githubusercontent.com/40236469/58232343-994bcb80-7d39-11e9-9559-cd129dee0c97.png)

**Comment by evshvarov** [comment]
Hi @KurroLopez ! Could you confirm please that this works now?

**Comment by KurroLopez** [comment]
Yes... Now is working fine
