### ISSUE TITLE
Question: How to link already EXISTING translations between ES-EN versions?

### ISSUE THREAD

**Issue by rcemper** [intersystems-community/developer-community#194]
copied from Skype
Question: How to link already EXISTING translations between ES-EN versions?
Actual example:
https://es.community.intersystems.com/post/uso-de-expresiones-regulares-en-objectscript
https://community.intersystems.com/post/using-regular-expressions-cach%C3%A9
as it is the exact translation just the link between is missing
?

**Comment by lelikone** [comment]
I Fix It!

**Comment by evshvarov** [comment]
Hi @rcemper! Could you please confirm that we can close this?

**Comment by rcemper** [comment]
Hi all,
confirm closing.
Robert

Am 02.07.2019 um 21:45 schrieb Evgeny Shvarov:

**Comment by rcemper** [comment]
Hi all,
confirm closing.

- robert

Am 02.07.2019 um 21:45 schrieb Evgeny Shvarov:
