### ISSUE TITLE
Add SOLVED signal to Questions

### ISSUE THREAD

**Issue by rcemper** [intersystems-community/developer-community#20]
The concept of "Accepted Answer" is mostly not understood by new ( also many old) members.
And there are cases where more than 1 single Answer is (partially) "correct".
e.g. https://community.intersystems.com/post/unable-send-emails-distribution-list
So I suggest having a button **SOLVED** that acts like "accept" without selecting a specific answer.
The mechanic behind is the same except the _specific_ single answer
![image](https://user-images.githubusercontent.com/31236645/40298833-b409e644-5ce4-11e8-8242-ea7c0993c51b.png)

----------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/31236645/40298928-fe8d4f76-5ce4-11e8-9c45-1fa43077b13d.png)

**Comment by evshvarov** [comment]
And you suggest to cancel the concept of Accepted answer at all?

**Comment by rcemper** [comment]
I suggest no replacement of the ACCEPTED ANSWER but an additional signal that the case is CLOSED or SOLVED somehow not by an answer. Ciao from the beaches of Italy. Robert 
-------- Ursprüngliche Nachricht --------Von: Evgeny Shvarov <notifications@github.com> Datum: 04.06.18  09:55  (GMT+01:00) An: intersystems-community/developer-community <developer-community@noreply.github.com> Cc: rcemper <robert@cemper.com>, Author <author@noreply.github.com> Betreff: Re: [intersystems-community/developer-community] Add SOLVED signal to
  Questions (#20) 
And you suggest to cancel the concept of Accepted answer at all?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/intersystems-community/developer-community/issues/20#issuecomment-394266319","url":"https://github.com/intersystems-community/developer-community/issues/20#issuecomment-394266319","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/intersystems-community/developer-community","title":"intersystems-community/developer-community","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/intersystems-community/developer-community"}},"updates":{"snippets":[{"icon":"PERSON","message":"@evshvarov in #20: And you suggest to cancel the concept of Accepted answer at all?"}],"action":{"name":"View Issue","url":"https://github.com/intersystems-community/developer-community/issues/20#issuecomment-394266319"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [intersystems-community/developer-community] Add SOLVED signal to Questions (#20)",
"sections": [
{
"text": "",
"activityTitle": "**Evgeny Shvarov**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@evshvarov",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"intersystems-community/developer-community\",\n\"issueId\": 20,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"intersystems-community/developer-community\",\n\"issueId\": 20\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/intersystems-community/developer-community/issues/20#issuecomment-394266319"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 337281001\n}"
}
],
"themeColor": "26292E"
}

**Comment by rcemper** [comment]
Great! Let's see how it works.
![unbenannt](https://user-images.githubusercontent.com/31236645/41212389-ce5b5866-6d3d-11e8-8e0d-c436f90ca321.JPG)
