### ISSUE TITLE
Unable to post something with Emoji

### ISSUE THREAD

**Issue by ZitRos** [intersystems-community/developer-community#204]
Previews for posts with Emojis work well, but once you press "post", you lose whatever you were editing:

![image](https://user-images.githubusercontent.com/4989256/59187230-a52eee80-8b7d-11e9-8a3b-ddf5154bfe24.png)

The particular Emoji that didn't work for me: 😄

Thanks! Let us smile 😊

**Comment by lelikone** [comment]
@ZitRos 
Hi!
Made an Emoji support

**Comment by nikitaeverywhere** [comment]
@lelikone awesome! Thanks 🤩

**Comment by nikitaeverywhere** [comment]
Seems to work now :) Thanks!
