### ISSUE TITLE
Please add link to 'GLOBAL MASTERS' to banner alongside 'OPEN EXCHANGE'

### ISSUE THREAD

**Issue by spdegabrielle** [intersystems-community/developer-community#216]
Please add link to 'GLOBAL MASTERS' to banner alongside 'OPEN EXCHANGE'
https://globalmasters.intersystems.com

**Comment by evshvarov** [comment]
@spdegabrielle  - this is done) close?

**Comment by spdegabrielle** [comment]
thank you
