### ISSUE TITLE
Please add 'Developer Community and 'Open Exchange' links to Global Masters banner.

### ISSUE THREAD

**Issue by spdegabrielle** [intersystems-community/developer-community#217]
Please add 'Developer Community and 'Open Exchange' links to Global Masters alongside 'Home Challenges Rewards' in the banner.

**Comment by evshvarov** [comment]
Global Masters is introduced: https://community.intersystems.com
can we close the task?

**Comment by spdegabrielle** [comment]
The Global Masters banner only has links to 'home'(forum), 'Challenges' and 'Rewards' in the banner at https://globalmasters.intersystems.com/forum/ 
This is a request to add 'OPEN EXCHANGE' and 'GLOBAL MASTERS' in the same way they appear on https://community.intersystems.com/

There is currently no way to navigate to community or exchange from global masters - which seems a shame given the interdependence of these sites.

Proposed:
![gp-proposed](https://user-images.githubusercontent.com/108047/61115424-5630ed80-a48a-11e9-9748-9b58e090cf95.png)

Current
![gm](https://user-images.githubusercontent.com/108047/61115429-592bde00-a48a-11e9-878d-bd424717c7f9.PNG)

Exchange banner
![exchange](https://user-images.githubusercontent.com/108047/61115433-5cbf6500-a48a-11e9-8590-acb3c27932ff.PNG)

Commmunity banner
![community](https://user-images.githubusercontent.com/108047/61115440-5f21bf00-a48a-11e9-8006-9d3de41ca173.PNG)

**Comment by evshvarov** [comment]
@spdegabrielle got you. It's not for Community, It's a different site - globalmasters.intersystems.com
