### ISSUE TITLE
Don't send notifications to user for his own actions

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#22]
Got this email for my answer in my own [question](https://community.intersystems.com/post/localize-deepsee-time-dimension). 
![image](https://user-images.githubusercontent.com/5127457/41094845-4bfb296a-6a58-11e8-9109-0cbaa663eb40.png)

**Comment by evshvarov** [comment]
@eduard93, this is fixed. Close?

**Comment by eduard93** [comment]
Got this again today.
`Dear Eduard Lebedyuk! Eduard Lebedyuk marked your answer to the question Iterate over %List/$lb in C as right.`

**Comment by lelikone** [comment]
fixed.

**Comment by evshvarov** [comment]
@eduard93 please close if it's done
