### ISSUE TITLE
 rel="alternate"

### ISSUE THREAD

**Issue by vmologa** [intersystems-community/developer-community#220]
Нужно перелинковать испанский и английский комьюнити. В хед страницы у которой есть альтернативная версия на другом языке нужно указать тег вида 
<link rel="alternate" hreflang="es" href="http://domain.es/" />
<link rel="alternate" hreflang="en" href="http://domain.com/" />
Это информация для поисковика, о том что у страницы есть альтернативная языковая версия

**Comment by evshvarov** [comment]
@vmologa сделано это? Закрываем?
