### ISSUE TITLE
Tag translations

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#228]
Hi!
there are some tags that are not correctly translated. Could you please change the translation?
![Captura de pantalla 2019-07-12 a las 12 38 13](https://user-images.githubusercontent.com/50864675/61122381-f34b5080-a4a1-11e9-8d99-e357b9854b80.png)
Thanks!
Esther

**Comment by lelikone** [comment]
@CM-DC-ES  Please send corrections in text format, you can attach the file

**Comment by CM-DC-ES** [comment]
ok, sorry. Is it correct with this document?
[Tag translations.docx](https://github.com/intersystems-community/developer-community/files/3386163/Tag.translations.docx)
Thanks
Esther

**Comment by lelikone** [comment]
Thanks

**Comment by evshvarov** [comment]
Perforce shouldn’t be translated, it’s a product

пт, 12 июля 2019 г. в 14:05, Aleksey Kanashevskiy <notifications@github.com

**Comment by CM-DC-ES** [comment]
Yes, Perforce is a product and shouldnt be translated. I agree. That's the reason why I put that word in the column "Correct translation".
My table has 2 columns- the second column shows the words that appear now in the Spanish version of the tag tree, and all of them are incorrect. So you have to take those words and replace all of them by the words in the first column (correct translation).
I'm not sure now if I was clear enough when writing the issue...
For any question about this, please let me know.
Thanks
Esther

**Comment by evshvarov** [comment]
Never mind - I just missed correct and wrong columns )

пт, 12 июля 2019 г. в 16:47, Евгений Шваров <evgeny.shvarov@gmail.com>:

**Comment by lelikone** [comment]
I already did

**Comment by CM-DC-ES** [comment]
Thanks!
