### ISSUE TITLE
Introduce polls in DC

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/developer-community#23]
Introduce a poll into a post to let DC members to vote for this or that

**Comment by daimor** [comment]
I want to use a poll in my next article, would it be possible to get it available asap?

**Comment by evshvarov** [comment]
No. Turned out it’s a relatively hard task to implement

вт, 2 апр. 2019 г. в 13:50, Dmitry Maslennikov <notifications@github.com>:
