### ISSUE TITLE
Optimize images on Developer Community

### ISSUE THREAD

**Issue by ssarkisy** [intersystems-community/developer-community#231]
Hello!

At the moment, there are some images in the sidebar of the main page of DC which use ~170x170 px container, but actualy load full-size 2000x2000 px images, ~1-2MB each(!).

![image](https://user-images.githubusercontent.com/8457295/61290701-2c066500-a7d5-11e9-8e3f-27af08b03f37.png)
 
Generally, this is a very bad practice. The best practice would be to optimize the images on the page for specific use cases. This should result in faster page loads and less traffic.

For example, here is image for machine learning webinar (original file size is 1.6MB), optimized for current use case (thumbnail 170px wide. The image actually is 340x340 px to support HiDPI displays). 
On the left is the lossless version and now it's file size is only 136KB. On the right is lossy version with even smaller file size of 44KB.

<img src="https://user-images.githubusercontent.com/8457295/61293231-e4cfa280-a7db-11e9-9422-ca1f5a566863.png" width="170"> <img src="https://user-images.githubusercontent.com/8457295/61293652-da61d880-a7dc-11e9-9ee1-aa91b0ad3682.jpg" width="170">

Thank you!

**Comment by Dyubaylo97** [comment]
Hi @ssarkisy,
Fixed! Please check it.
