### ISSUE TITLE
Translate text label wrong if you select a type of post

### ISSUE THREAD

**Issue by KurroLopez** [intersystems-community/developer-community#233]
#### Describe the problem you're observing:
If you create a new post (https://es.community.intersystems.com) the label of the text is wrong according to type of post.

#### Steps to reproduce, if exist:
Type of message (Tipo de mensaje) -> Label of text
Pregunta (Question) -> Hacer un nuevo resumen (Make a new Digest)
Anuncio (Announcement) -> Haz una pregunta (Make a new question)
Artículo (Article) -> Hacer un anuncio (Make a new Announcement)
Resumen (Digest) -> Hacer un nuevo post (Make a new Post)

**Comment by lelikone** [comment]
@KurroLopez 
Hi! Please check it.

**Comment by KurroLopez** [comment]
Checked... now it's fine.

Thanks.

*Francisco Lopez*


*Twitter: @KurroLopezLinkedin:
https://www.linkedin.com/in/franciscolopezdelasheras/
<https://www.linkedin.com/in/franciscolopezdelasheras/>*

**Comment by KurroLopez** [comment]
I've noted now that the Digest type ("Tipo de resumen") is not displayed
when Digest ("Resumen") is selected. Only in spanish DC

*Francisco Lopez*


*Twitter: @KurroLopezLinkedin:
https://www.linkedin.com/in/franciscolopezdelasheras/
<https://www.linkedin.com/in/franciscolopezdelasheras/>*

**Comment by lelikone** [comment]
@KurroLopez fixed

**Comment by KurroLopez** [comment]
Fine, good job
