### ISSUE TITLE
Make member profile details visible without login for trusted members

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/developer-community#235]
The filter "Trusted" is mandatory to avoid spam links in bio

**Comment by lelikone** [comment]
Re: [intersystems-community/developer-community] Make member profile details visible without login for trusted members (#235)



Здравствуйте, InterSystems.

Вот так у нас будут на комьюнити выглядеть ответы

С уважением, Алексей Канашевский                           
тел.: (3952) 76-11-33
e-mail:lelikone@mail.ru
-- 
Tuesday, June 18, 2019, 1:51:03 AM, Вы писали:














Dmitry Maslennikov añadió una nueva artículo GitHub ahora soporta ObjectScript
Oye, desarrolladores, tengo una gran noticia para ti. Hace unos días, GitHub se actualizó con la última versión del proyecto linguist, que se utiliza para reconocer los tipos de código fuente en los repositorios. Ayuda a determinar qué lenguaje de programación se ha utilizado en cada archivo del repositorio. La sección de estadísticas del repositorio muestra los resultados de este trabajo de módulo.
 
Además, puede buscar en todos los repositorios disponibles de GitHub para cualquier idioma elegido.Por ejemplo, consulte las estadísticas de idiomas del propio proyecto lingust.
¡Y el último lanzamiento de linguist viene sintaxis de ObjectScript!

El nivel de resaltado no es tan perfecto como esperaba. Lunguist utiliza la gramática de TextMate definida en este repositorio. Se basa en lo que utilicé en la extensión VSCode para ObjectScript. Entonces, idealmente, debería tener un resaltado muy similar. Si tiene alguna idea sobre cómo mejorar nuestra gramática de TextMate para ObjectScript, de nada.
Por lo tanto, GitHub ahora puede reconocer archivos con extensión CLS como código ObjectScript.
No reconoce ningún otro tipo de nuestro, como MAC, INT, INC. Puede considerarlo como un idioma diferente o ignorarlo en absoluto. Pero si puede cambiar este comportamiento para su repositorio, cambie el archivo .gitattributes.
# Example of a `.gitattributes` file which reclassifies `.mac` and `.inc` files as ObjectScript:
*.mac linguist-language=ObjectScript
*.inc linguist-language=ObjectScript
El cambio solo afecta a las estadísticas, pero no al resaltado de sintaxis. Por lo tanto, mac e inc todavía se muestran sin ningún resaltado.
Cuando agregue este archivo en su repositorio, las estadísticas ahora contarán este archivo, y el resaltado de sintaxis también funcionará.

 
Article por Dmitry Maslennikov 17 June 2019
Ambiente de desarrollo, Idiomas, ObjectScript, Otro
Ver publicacion Suscribir

Usted está recibiendo este correo electrónico porque es miembro de Comunidad de desarrolladores de InterSystems.
Si quiere gestionar sus suscripciones, siga este enlace Administrar suscripciones.
















--
