### ISSUE TITLE
Translation tab not visible

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#242]
#### Describe the problem you're observing:
There are no links between the original and translated version of articles. And translate tab not visible.

#### Steps to reproduce, if exist:
English original
https://community.intersystems.com/post/vscode-objectscript-release-0711
![image](https://user-images.githubusercontent.com/1212251/62045119-39781200-b20d-11e9-9efa-4af0b9fbee8a.png)

Spanish translation
https://es.community.intersystems.com/post/nueva-versi%C3%B3n-de-vscode-objectscript-0711
![image](https://user-images.githubusercontent.com/1212251/62045136-48f75b00-b20d-11e9-9794-db212efa85c0.png)

**Comment by lelikone** [comment]
@daimor 
Only articles and questions are available for translation, Announcement are not available for translation

**Comment by daimor** [comment]
Why not? would it be possible to support announcements too?

**Comment by lelikone** [comment]
@daimor 
I've made a support announcement.

**Comment by evshvarov** [comment]
@daimor please close if it's done

**Comment by evshvarov** [comment]
@daimor could you please check if this works now? and close? )
