### ISSUE TITLE
Shorter monthly digests

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#245]
Hi! I'd like to see a friendlier monthly digest. These are my proposals:
* Each part of the digest should show only <b>5 posts</b>, and then another item saying something like "Have a look at the rest of the list here >>" with a link to the webpage with the rest of the posts, filtered by period and also by votes or by views.
For example: "The most viewed" part- would show 5 posts and then this link: https://community.intersystems.com/?sort=viewed&period=lastmonth
* As there is no <b>filter "By comments"</b>, it should be added
* The "top 10" authors/experts should be replaced by the <b>"top 5"</b>. Less authors/experts, more value you give to them. And all the authors will be looking forward to being in that "top 5"
* In the "Most viewed", "Most voted" and "Most discussed" parts, the <b>type of post</b> should be added before the name of each author.
For example: 
Interface monitoring
<u>Question</u> by Erin Dolson

Thanks! 
Esther

**Comment by evshvarov** [comment]
Hi Esther! all makes sense. @lelikone, let's plan for the next month

**Comment by evshvarov** [comment]
Happily, we have these links now for sorting posts by votes and views in a given month, so we can reduce items to 5 and provide a link.

**Comment by CM-DC-ES** [comment]
Great! Thanks! :)

**Comment by lelikone** [comment]
@CM-DC-ES 
Hi Esther! 
please translate:
View all most viewed posts
View all most voted posts
View all most discussed posts

**Comment by CM-DC-ES** [comment]
Hi! Sure!
* Ver todos los posts más vistos
* Ver todos los posts más votados
* Ver todos los posts más comentados
Esther
