### ISSUE TITLE
Add all the tags to the drop-down menu of the articles

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#249]
Hi!
I've noticed that not all the tags in Spanish have been added to the drop-down menu where you select the tags for an article.
For example: when you look for the tag "Resumen" on the select box, it doesnt appear, although it is already in the tag tree.
![Captura de pantalla 2019-08-02 a las 13 45 24](https://user-images.githubusercontent.com/50864675/62368222-4c9c2200-b52c-11e9-8a79-b9c18d3a9469.png)

![Captura de pantalla 2019-08-02 a las 13 47 16](https://user-images.githubusercontent.com/50864675/62368239-5756b700-b52c-11e9-91d4-df0108ad3acb.png)
Could you please check that all the Spanish tags are in the drop-down menu?
And the tags should be put in alphabetical order, too.
Thanks!
Esther

**Comment by lelikone** [comment]
@CM-DC-ES 
All tags are on the drop-down menu. Tag "Resumen" is available to a limited number of participants.

**Comment by CM-DC-ES** [comment]
Hi!
In that case, I should be able to use the tag "Resumen" (Digest), since I'm the person in charge of doing the digests in Spanish...
And please, put the tags in alphabetical order. Now they are in disorder, see screenshot:
![Captura de pantalla 2019-08-05 a las 10 03 15](https://user-images.githubusercontent.com/50864675/62448528-5a3deb80-b768-11e9-87cd-f92c350bd85c.png)
Thanks
Esther

**Comment by evshvarov** [comment]
Esther, do you know you can start typing and it will find you the tag? Just
in case

**Comment by CM-DC-ES** [comment]
Sure, I know! so call me maniac, but I like to see the drop-down menus in order (if possible) :-O
Thanks!
Esther

**Comment by evshvarov** [comment]
No worries, asked just in case ) I think everything is possible with
Aleksei )

**Comment by lelikone** [comment]
@CM-DC-ES 
Hi Esther!
I did a sorting by name.

**Comment by CM-DC-ES** [comment]
Great! Thanks!
What about the tag "Resumen". Could I use it?
Esther

**Comment by lelikone** [comment]
Yes
input type Etiquetas
