### ISSUE TITLE
Can't see the view mode properly

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#252]
Hi!
the view mode in this article is wrong!
https://es.community.intersystems.com/post/mapas-de-url-avanzados-para-rest
how can I fix it?
![Captura de pantalla 2019-08-08 a las 12 16 51](https://user-images.githubusercontent.com/50864675/62695467-b27a2500-b9d6-11e9-809c-ae3427966b2c.png)

**Comment by lelikone** [comment]
@CM-DC-ES 
This text should only be edited manually

**Comment by CM-DC-ES** [comment]
ok, I dont know why appeared like that. Anyway, I have edited the text again and it's ok now. 
Hope it keeps the view correctly!
Esther
