### ISSUE TITLE
Can't add a translated post

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#253]
Hi!
I want to add the translation to this post: "Global time management". The author has given me permission, but when I click on "Add translated post", I get a "Page not found" error message. Could you help me to solve the issue?
Thanks!
Esther

**Comment by lelikone** [comment]
@CM-DC-ES 
Hi Esther!
Someone already translated for this article and the article was deleted. I have cancelled this and now I have to make a new translation request.

**Comment by lelikone** [comment]
@CM-DC-ES 
Hi Esther! Close issue?

**Comment by CM-DC-ES** [comment]
Hi! Sorry, I didnt answer you.
I have added the translated article in Spanish again, but it seems that is not linked to the English version. That is, when I click on the "Traducción" tab, I can see the original article. But when I click on the "EN" button, I see the "Page not found" message.
https://es.community.intersystems.com/post/gesti%C3%B3n-del-tiempo-internacional
Any suggestion to solve this?
Thanks
Esther
