### ISSUE TITLE
Article searchable but cannot be opened

### ISSUE THREAD

**Issue by lilytaub** [intersystems-community/developer-community#256]
#### Describe the problem you're observing:
The article at the link below is searchable in the developer community, but receives an HTTP 403 error when one tries to view it.
[Top 10 DevOps Tools for Continuous Development](https://community.intersystems.com/post/top-10-devops-tools-continuous-integration)
#### Steps to reproduce, if exist:
Search the Developer Community for articles with the "DevOps" tag. The above is returned as the first hit.

**Comment by lelikone** [comment]
@lilytaub 
This content is blocked. Fixed an error in the appearance of such content in search results.

**Comment by evshvarov** [comment]
Hi @lilytaub ! Could you please close the issue if it's done?

**Comment by lilytaub** [comment]
closing issue
