### ISSUE TITLE
Add new type of post Job Opportunity

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/developer-community#257]
If you add an announcement, which has Job Opportunity tag this adds a special button Apply for a job.
This sends a direct message to an account with the text:
Contact me, I'm interested.

Add the status of Job Opportunity. It could be Open (green) and Closed - red.
The status could be changed by the author - add button Close opportunity.

**Comment by lelikone** [comment]
send DM for author
"I’m interested in this opportunity. Please email me the details: member_email"

if inserted tag "Job Opportunity" -show button (I’m interested) and status Open/Closed?

**Comment by evshvarov** [comment]
Yes

ср, 28 авг. 2019 г. в 16:47, Aleksey Kanashevskiy <notifications@github.com
