### ISSUE TITLE
Suggestion: rename the "Developer Community" tag

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#26]
Some people posting articles seem to select the "Developer Community" tag for their post in the mistaken belief this is a way of asking the Developer Community for help. Of course ANY post can be one that asks DC for help. IMO the "Developer Community" tag should be reserved for posts/questions about the DC platform. So I propose we rename the "Developer Community" tag to "DC Platform". Using the abbreviation is deliberate, as I think it will discourage people from picking the tag unless they know what "DC Platform" means.

**Comment by eduard93** [comment]
Not sure about specific name, but definitely agree with you on the main renaming idea, @gjsjohnmurray.
`DC feedback` maybe? The word `Platform` is often used in `Data Platform`.

**Comment by gjsjohnmurray** [comment]
I support the proposal of @eduard93

**Comment by rcemper** [comment]
I vote for DC feedback

**Comment by evshvarov** [comment]
Done: https://community.intersystems.com/tags/dc-feedback

**Comment by evshvarov** [comment]
I updated tag description too. Please close if it is OK.

**Comment by rcemper** [comment]
great, thanks

**Comment by gjsjohnmurray** [comment]
Yes, it's good. Closing.
