### ISSUE TITLE
"I want to translate the article" button

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#261]
Hi!
when you click on the ES or EN button to translate a question, you get the message: "I want to translate the article" or "Quiero traducir el artículo" but you are not asking to translate an ARTICLE, but a QUESTION... So just wondering if you could change that sentence when asking for the translation of a question? In Spanish it would be "Quiero traducir la pregunta".
Thanks!
Esther

**Comment by lelikone** [comment]
@CM-DC-ES 
Hi!
I'm working on it now.
Here are the new texts that need translation:

Link to the translated article, if the article has already been translated.

Link to the translated announcement, if the announcement has already been translated.

Link to the translated question, if the question has already been translated.

I want to translate the article

I want to translate the announcement

I want to translate the question

**Comment by CM-DC-ES** [comment]
Hi! these are the translations:

Link to the translated article, if the article has already been translated.
Enlace al artículo traducido, si ya ha sido traducido.

Link to the translated announcement, if the announcement has already been translated.
Enlace al anuncio traducido, si ya ha sido traducido.

Link to the translated question, if the question has already been translated.
Enlace a la pregunta traducida, si ya ha sido traducida.

I want to translate the article
Me gustaría traducir este artículo

I want to translate the announcement
Me gustaría traducir este anuncio

I want to translate the question
Me gustaría traducir esta pregunta

**Comment by lelikone** [comment]
@CM-DC-ES 
Esther, check it out, is everything okay now?

**Comment by CM-DC-ES** [comment]
Yes, great! Thanks!! :)
