### ISSUE TITLE
Incorrect link in email digest

### ISSUE THREAD

**Issue by jtsalten** [intersystems-community/developer-community#262]
I've seen that an article published in the spanish community is incorrect. I see that the link points out to the "potential" english version... but not it that's not exist it fails.

Sample of today (email digest sent 29-August 11:34): 

Article published by Alberto Fuentes: Link should be: https://es.community.intersystems.com/post/configurar-un-servicio-rest-en-iam-y-publicarlo-en-el-developer-portal

but the main link in the header (marked yeallow) is wrong:
https://community.intersystems.com/post/configurar-un-servicio-rest-en-iam-y-publicarlo-en-el-developer-portal

![imagen](https://user-images.githubusercontent.com/6997495/63934109-e4712b00-ca5a-11e9-9df6-562a06865958.png)

**Comment by lelikone** [comment]
Thank you! I will study this problem.

**Comment by lelikone** [comment]
@jtsalten New digests should come with the right link, check.

**Comment by evshvarov** [comment]
Hi @jtsalten ! Could you please close if this is done?
