### ISSUE TITLE
Emails Language is Messed Up

### ISSUE THREAD

**Issue by nikitaeverywhere** [intersystems-community/developer-community#265]
Hello!

It's been around 2 months since I started to get emails from Developer Community in the language I don't understand (see the screenshots below). It would be nice if you could check what's wrong here (my email start with `zitros`) and that there are no other users that suffer from the same issue :) The website is displayed in English, no issues.

Thanks!

Nikita

![image](https://user-images.githubusercontent.com/4989256/64105349-bce1d180-cd7e-11e9-8b0d-744983e707bd.png)
![image](https://user-images.githubusercontent.com/4989256/64105329-b4899680-cd7e-11e9-9238-fd112d96d6ee.png)

**Comment by evshvarov** [comment]
Hi Nikita!
It's because when you opened Spanish DC you didn't refuse to receive
notifications - it asks in English when you get there for the first time.
You can turn it off in your Spanish DC
<http://es.community.intersystems.com> profile subscription settings.

**Comment by evshvarov** [comment]
Or you can click on the link in the bottom of the email.

**Comment by nikitaeverywhere** [comment]
Thanks, Evgeny!

Hmm. The link "unsubscribe" in email brings me to https://community.intersystems.com. So I've prepended `es.` and un-ticked all checkboxes there. Then I checked English website version again and it seems that yep, checkboxes are active there. Hope to continue receiving developer community updates! Thanks!
