### ISSUE TITLE
Open GitHub in a new window

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#272]
When clicking on About/Report an issue on the DC in Spanish, GitHub is opened in the same window, so you leave the DC and are directed to GitHub.
So just wondering if GitHub could be opened in a new window, as in the DC in English? :)
Thanks!
Esther

**Comment by lelikone** [comment]
@CM-DC-ES 
I did it.

**Comment by evshvarov** [comment]
@CM-DC-ES, Esther! Could you please close the issue? )

**Comment by CM-DC-ES** [comment]
Done! Thanks! :)
