### ISSUE TITLE
Pin a post in the DC in Spanish

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#285]
Hi,
just wondering if we could have a post pinned at the DC in Spanish?
The idea would be to use it just for events, webinars... until the day of the event. So we should have the option to unpin the posts, too.
That way, all the developers will remember the event each time they open the DC site.
Thanks!
Esther

**Comment by eduard93** [comment]
There's event panel on the right side, can you use it?

![image](https://user-images.githubusercontent.com/5127457/66417226-36b54c80-ea08-11e9-8b85-f89caec166dc.png)

**Comment by CM-DC-ES** [comment]
Yes, we can see it. But it happens the same with that panel- new events push down our event and it's not visible when you open the page. That's the reason why we prefer to pin a post, to keep it fixed for some days. Don't know if that is possible...
Thanks!
Esther

**Comment by evshvarov** [comment]
@CM-DC-ES , close please?

**Comment by CM-DC-ES** [comment]
Thanks! :)
