### ISSUE TITLE
Subjects in Spanish

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#292]
Hi,
could you please change the subjects in Spanish? the adjectives are not translated correctly now:
* Nuevas artículo -> Nuevo artículo
* Nuevas anuncio -> Nuevo anuncio
* Nuevas pregunta -> Nueva pregunta
Thanks!
Esther

**Comment by evshvarov** [comment]
@CM-DC-ES , Esther! Could you please close this if it is fixed?
