### ISSUE TITLE
Highlight new comments/answers since last view

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#294]
One of the latest great [post](https://community.intersystems.com/post/and-if-one-line-brace-or-not-brace) has already about 50 comments in it. And it's a bit difficult now to find what was written last there. So, I think we need some highlighting for comments or answers added since the last user's view. For instance, habr.com has such a feature.

**Comment by lelikone** [comment]
![image](https://user-images.githubusercontent.com/21163767/68284203-ff45c880-00b7-11ea-9284-3bddc0ab2af5.png)
@daimor Hello! I made a "NEW" tag for messages you haven't seen before.
