### ISSUE TITLE
Tag doubling error

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#295]
![photo_2019-10-23_14-23-42](https://user-images.githubusercontent.com/25077319/67388135-c9292480-f5a0-11e9-9e85-b14ee6608cc6.jpg)
![photo_2019-10-23_14-23-34](https://user-images.githubusercontent.com/25077319/67388136-c9c1bb00-f5a0-11e9-90ae-1577701152bc.jpg)

@lelikone

**Comment by evshvarov** [comment]
@Dyubaylo97 ? ) closing? )
