### ISSUE TITLE
Changes in "Prev & Next Announcement" feature

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#299]
**1.** Change text after the announcement: Add symbols ":" and "."
For example: Also, check the previous part ...text ---> Also, check the previous part: ...text.

**2.** New button layout
![Без имени-1](https://user-images.githubusercontent.com/25077319/67550600-8cc80680-f70f-11e9-82b6-4222f4a226cb.jpg)
@lelikone

**Comment by evshvarov** [comment]
@Dyubaylo97 , please close the feature if it is fixed?
