### ISSUE TITLE
Add feature to Convert Answer to Comment and Comment to Answer for Author of the Comment/Answer and moderators

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/developer-community#31]
Sometimes the comment is actually an answer for the question. And on the other hand, answer is not a answer, but comment.
E.g. here:
https://community.intersystems.com/node/449166

Add the button on the right corner of comment/answer to convert it to Answer or to Comment for the author and moderators.

Button is not available for answers which are accepted

**Comment by rcemper** [comment]
excellent!
I've seen several similar cases where participant didn't get the difference.
I just recently had the problem that during the elaboration of a comment it turned out that it became an answer.

**Comment by rcemper** [comment]
What about blocking also DELETE button for accepted answers ?

**Comment by evshvarov** [comment]
Yes, it was a demanded feature

**Comment by evshvarov** [comment]
Make a request? )

**Comment by evshvarov** [comment]
Done
