### ISSUE TITLE
New direct messages note

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#312]
**Is your feature request related to a problem? Please describe.**
No way to see if there are some new direct messages for the member from the home page.

**Describe the solution you'd like**
Close to the member name, or somewhere else, little letter icon with the number of unread direct messages, with highlighting if more then 0.
This icon also should redirect to direct messages page.

**Comment by lelikone** [comment]
@daimor 
Now you can see how many new messages you have.
![image](https://user-images.githubusercontent.com/21163767/70383408-7bc61280-19a8-11ea-97c7-1b54238f14c7.png)
