### ISSUE TITLE
"Mensaje Directo" tab in English DC version

### ISSUE THREAD

**Issue by psteiwer-isc** [intersystems-community/developer-community#317]
When viewing the "My Account" page, one of the tabs is in Spanish when using the English version of DC.

The tab for direct message is says "Mensaje Directo"

https://community.intersystems.com/user

**Comment by lelikone** [comment]
@psteiwer-isc Now ok?

**Comment by evshvarov** [comment]
@psteiwer-isc, please close? )

**Comment by evshvarov** [comment]
@psteiwer-isc, close please the issue if this is fixed?
