### ISSUE TITLE
Add Certification Star / Badge on Community Profile

### ISSUE THREAD

**Issue by vneerav** [intersystems-community/developer-community#324]
Hello,

To highlight individuals who have passed Intersystems certification we should have the ability to add a badge / star to their profile. 

Also ability to add multiple certifications to add to their profile

**Comment by lelikone** [comment]
by way of example
https://community.intersystems.com/post/get-certified-intersystems-iris-development
https://intersystems.credly.com/member-badges/22303811

**Comment by lelikone** [comment]
we cannot automatically load credentials for anyone. It has to be their decision to publish a credential.

**Comment by spdegabrielle** [comment]
I put mine in my profile  'git/web url' field but that is obviously a bit rubbish. 
A better decision was to add the badge to my GitHub profile readme where it is more likely to be seen.

**Comment by Lena-Ev** [comment]
Hey guys!
I see that the issue is a little bit overdue, but we found the way we want to do that.
We will get certificates from credly and will mark certified usesrs. We are also going to add new page with the list of certificates.
The work is in progress.

**Comment by Lena-Ev** [comment]
We finally did it :)

Now you can add your certificates issued on Credly, and if you have ones your profile will show a sign that you are certified developer

![Image](https://user-images.githubusercontent.com/77621970/193875068-aa42cf79-c539-41f6-ab63-8c58ddf5739b.png)



![Image](https://user-images.githubusercontent.com/77621970/193875137-ed547890-bd28-4698-b8cd-37fcbd4bd82c.png)
