### ISSUE TITLE
Edit Avatar Picture on Community

### ISSUE THREAD

**Issue by vneerav** [intersystems-community/developer-community#325]
**Is your feature request related to a problem? Please describe.**
There is no option to update the profile/avatar pic on community profile

**Describe the solution you'd like**
- Need to have a way to update the profile pic

**Describe alternatives you've considered**

**Additional context**

**Comment by lelikone** [comment]
@vneerav 
Hi. You have this opportunity. To do this, you need to login to your account by clicking on the link at the top of the site.
Then you should go to the edit mode by clicking the edit link.
![image](https://user-images.githubusercontent.com/21163767/70369655-eff4ad80-18f7-11ea-8d26-a0d347c6585d.png)
You can upload avatars in edit mode. Supported formats are JPG, PNG, GIF. The size of the uploaded file is not more than 2 mb.
![image](https://user-images.githubusercontent.com/21163767/70369701-609bca00-18f8-11ea-8944-998c30e5b692.png)

**Comment by evshvarov** [comment]
@vneerav does it work for you now? Close, please?

**Comment by vneerav** [comment]
Yes
Thank You
