### ISSUE TITLE
Error when accesing Nancy Martinez's profil

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#332]
Hi!
When I try to access Nancy Martinez's profile, I get an error page. And it just happens with Nancy, not other members.. 
This is the message I get:
![image](https://user-images.githubusercontent.com/50864675/71077271-65c60800-2187-11ea-8cb8-678825872eee.png)
Could you solve the issue for me?
Thanks!
ES

**Comment by evshvarov** [comment]
@CM-DC-ES was this fixed? Close please?

**Comment by CM-DC-ES** [comment]
Hi Evgeny!
No, was not fixed. I still get an error message.
![imagen](https://user-images.githubusercontent.com/50864675/71655112-b0be4e80-2d35-11ea-8a98-8540eb5a76ec.png)
Thanks
Esther

**Comment by CM-DC-ES** [comment]
Hi! Could you fix this for me, please?
Thanks!
ES

**Comment by evshvarov** [comment]
What is the link, Esther?

**Comment by CM-DC-ES** [comment]
https://es.community.intersystems.com/user/nancy-mart%C3%ADnez

**Comment by lelikone** [comment]
@CM-DC-ES 
It's got to be right now. Check out .

**Comment by CM-DC-ES** [comment]
Great! Thanks! 👍
