### ISSUE TITLE
Annual digest

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#333]
Create an annual digest. Similar to the monthly digest, but with the most viewed, most voted, most discussed... of the whole year. 
Separate digest on Questions and separate on Articles. For Announcements, it is not needed.
Both for Spanish and English Community. 
@lelikone

**Comment by lelikone** [comment]
Digest for Articles:
Most viewed 
Most voted
Most Discussed
Top 5 Authors to Follow by Views

Digest for Questions:
Most viewed 
Most voted
Most Discussed
Top 5 Experts to Follow

TOP 20
