### ISSUE TITLE
Editor replaces duplicate linebreaks with singular linebreaks in code fragments

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#334]
#### Describe the problem you're observing:

When I either create a new code fragment from existing text, or 9even more importantly) open existing code fragment to edit all duplicate linebreaks are transformed into singular line breaks.

#### Expected behavior

Duplicate linebreaks are left as is

#### Steps to reproduce, if exist:

1. Open page with any [code sample](https://community.intersystems.com/post/query-result-save-csv).
2. See this 
![image](https://user-images.githubusercontent.com/5127457/71310182-2c5cf900-2422-11ea-967b-f941ada3b4a9.png)
3. Press `Edit answer`. Formatting is immediately lost (without any editing)
![image](https://user-images.githubusercontent.com/5127457/71310193-4991c780-2422-11ea-866d-cee0b3101da1.png)
4. Saving would remove linebreaks completely. Same for creating new code fragment.

**Comment by evshvarov** [comment]
@eduard93 close please?
