### ISSUE TITLE
Separate the file uploader

### ISSUE THREAD

**Issue by rfns** [intersystems-community/developer-community#349]
**Is your feature request related to a problem? Please describe.**
Add a way to upload images without using the WYSIWYG editor.

**Describe the solution you'd like**
Maybe creating an individual upload module that can be used for both editors instead of using the embedded one. This one should display the direct link to the uploaded image so that both editors can use.

**Describe alternatives you've considered**
There's a way to use the image uploader even though the selected editor is the one using Markdown: just upload the file previosuly using the WYSIWYG, get the URL and paste using the Markdown image format.

But this is not usable at all.

**Comment by lelikone** [comment]
@rfns 
Hi!
I added the ability to upload images when creating an article when editing in markdown
![image](https://user-images.githubusercontent.com/21163767/82136393-37388000-9840-11ea-9716-53e6de775f75.png)

**Comment by rfns** [comment]
@lelikone thank you, but please also add that toolbar to the replies if possible.

![image](https://user-images.githubusercontent.com/3527583/82741821-a9bbcb00-9d2c-11ea-8e7f-dacad63a5d65.png)
