### ISSUE TITLE
block Delete and Edit button on Accepted answers

### ISSUE THREAD

**Issue by rcemper** [intersystems-community/developer-community#35]
Actually, this seems to be possible. I'd expected it to be frozen
But an added comment may do the same without destroying the original
Similar for an update. (e.g because of a new version)

**Comment by evshvarov** [comment]
@rcemper Check it please?

**Comment by lelikone** [comment]
@rcemper Check it please?

**Comment by rcemper** [comment]
I just reached this page with accepted answer.
https://community.intersystems.com/node/450681/edit
It might be due to Moderators rights. So the risk of error is limited.
But it can't be deleted. 
Only changed (Save) or unpublished!  That's OK
