### ISSUE TITLE
Add 'Creation Date' sorting

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#352]
Please add 'Creation Date' sorting option here:
![image](https://user-images.githubusercontent.com/5127457/73755772-95e95a80-4777-11ea-88c8-81c4b1d96eaf.png)

Can be useful for users who a regularly on DC and just want to see newly created posts.

**Comment by lelikone** [comment]
@eduard93 
Sorting is done, check. If all is well, close the task.

![image](https://user-images.githubusercontent.com/21163767/73899829-c391e900-48c8-11ea-9c3c-abdb40dc5b81.png)
