### ISSUE TITLE
Add questionX -> node/X redirect

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#373]
1. Search for: `site:community.intersystems.com Demo.ZenService`
2. Google results point to https://community.intersystems.com/question437621/answer437631
3. It's not a valid link, it should be https://community.intersystems.com/node/437621/answer437631 instead(althrough answer437631 does not focus correctly, but at least the page opens).

I think we need to add redirect: questionX -> node/X

**Comment by lelikone** [comment]
@eduard93 
Hello, Edward.
I've just forwarded from these addresses to the right one.
Unfortunately, the site now has no answers, and there is no link to them.
Will you check if I've done the right thing? If you did, then close the task.
