### ISSUE TITLE
Incorrectly converted time for events

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#387]
For example
https://community.intersystems.com/post/test-event1
When event configured in particular timezone, post shows timezone selected in post, but time different, depends on a timezone which set in member's settings. Only member's Moscow's time shows the correct time in post.

When members not logged in it shows without correction, so, shows correctly as configured.

I suppose block with time in event's post should show correct time in members timezone, with correct suffix.
e.g. if use in MSK time zone, he should see any event with the correct time in his timezone.

Now, for event at 10:00 MSK(UTC+3), and member's timezone UTC. Post shows time as 01:00 PM MSK, when it should be 10:00 MSK or more preferable 07:00 UTC.

For a member in New York, it shows 05:00 PM MSK, while expected to be 03:00 AM EDT.

When edit post after change timezone, it shows different times in the field.

**Comment by lelikone** [comment]
@daimor
Hello, Dimitri. I've made changes on the site, check it out, is it done correctly?
