### ISSUE TITLE
Email notification for unaccepted answers

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#390]
Make an additional email notification to posts with answers, but without an accepted answer. So the authors accept answers and the question becomes closed.
@lelikone

**Comment by lelikone** [comment]
https://docs.google.com/document/d/1ZfPLMZC-JUzOz04piitXnlInhaBXZV0MSpJyhcww3SM/edit

**Comment by lelikone** [comment]
1. Each new answer starts the cycle: after 3 days
2. In a week (you have answers that are not accepted in this question).
3. A month from now (see, what if one of them is the answer?)
