### ISSUE TITLE
"Alertas" tag

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#391]
Hi there!
I've realised that there is a tag called "Alertas" in the Spanish tag cloud (https://es.community.intersystems.com/tagsclouds) but when I want to add that tag to an announcement, it doesnt appear in the drop-down menu to be selected...
![imagen](https://user-images.githubusercontent.com/50864675/79103261-89334500-7d6c-11ea-83ee-fd01b5ce9af5.png)
![imagen](https://user-images.githubusercontent.com/50864675/79103290-96e8ca80-7d6c-11ea-8599-722fb961c036.png)

So just wondering if you could fix this so I could choose the tag in the drop-down menu?
Thanks
 Esther

**Comment by lelikone** [comment]
@CM-DC-ES 
Hi!
I gave the Alertas Tag a free pass.

**Comment by CM-DC-ES** [comment]
Great! Thanks! :)
