### ISSUE TITLE
GM & DC integration: Contests Roles

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#393]
Make the integration of levels between the community and GM, so that the contest roles are determined automatically.
When an advocate move to another level, his/her contest role changes automatically.
@lelikone

**Comment by lelikone** [comment]
https://influitive.readme.io/docs
https://support.influitive.com/article/391-influitive-api
https://influitive.readme.io/reference#getting-started

**Comment by lelikone** [comment]
https://influitive.readme.io/reference#updated-advocates

**Comment by evshvarov** [comment]
@Dyubaylo97 Does it work?
