### ISSUE TITLE
Automatic DM for the Contest Voting

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#394]
Make an automatic direct message for the Contest Voting to DC members with different GM levels.

1. For Experts - https://community.intersystems.com/post/expert-iris-programming-contest-we-need-your-vote
2. For Specialists - https://community.intersystems.com/post/specialist-iris-programming-contest-we-need-your-vote

@lelikone

**Comment by evshvarov** [comment]
@Dyubaylo97 works?
