### ISSUE TITLE
Clinical Viewer Local Version Giving Error Message. Pls help

### ISSUE THREAD

**Issue by bukhtiarahmad** [intersystems-community/developer-community#421]
Hi I installed community version of clinical viewer and while pressing Start All button I am getting below error message, any idea may be i am missing some of the configuration in the installation wizard. 
Pls help

18:38:55.203:HS.Director: Switching to namespace 'CLINICALVIEWER' [AccessGateway]
18:38:55.239:Ens.Director: Production 'CLINICALVIEWERPKG.AccessGatewayProduction' starting...
Failed to configure synchronization

18:38:56.117:...GatewayProduction: Startup Error 0 é6248Server Application Error¾0zInvokeHubService+25^%ZHSLIB.Services.Client.1CLINICALVIEWERz4e^zInvokeHubService+25^%ZHSLIB.Services.Client.1^15e^zSyncConfiguration+25^%ZHSLIB.Services.Client.1^1.e^zOnStart+40^HS.Util.AbstractProduction.1^13e^zOnStart+1^HS.Util.AbstractAccessProduction.1^1(e^zStartProduction+41^Ens.Director.1^1(e^zStartProduction+8^%SYS.Ensemble.1^1'e^zStartProduction+8^Ens.Director.1^1-e^zinvokeMethod+22^|"HSLIB"|HS.Director.1^1*e^zinvokeAll+28^|"HSLIB"|HS.Director.1^1(e^zStartAll+1^|"HSLIB"|HS.Director.1^19e^zStartProductions+2^|"HSLIB"|HS.UI.StartStopFrame.1^10e^zOnPage+24^|"HSLIB"|HS.UI.StartStopFrame.1^18e^zPage+9^|"HSLIB"|EnsPortal.Template.standardPage.1^2$e^CSPDispatch+480^%SYS.cspServer^2$d^CSPDispatch+274^%SYS.cspServer^1&d^zProcessRequest+1^%CSP.Session.1^1!d^Request+668^%SYS.cspServer2^1 d^Request+25^%SYS.cspServer2^1&d^zProcessRequest+1^%CSP.Request.1^1d^css+43^%SYS.cspServer2^1 d^SuperServer+55^%SYS.SERVER^3d^^^0
18:38:56.118:Ens.Director: ERROR #6248: SOAP response is a SOAP fault: Server Application Error
18:38:56.119:Ens.Director: ERROR #6248: SOAP response is a SOAP fault: Server Application ErrorERROR #6248: SOAP response is a SOAP fault: Server Application Error

**Comment by evshvarov** [comment]
Hi @bukhtiarahmad ! This questions are for the forum](https://community.intersystems.com/)
Here we accept issues if oyu want to improve the forum.
So I'm closing it!
