### ISSUE TITLE
Export to PDF/Print Post - Access denied

### ISSUE THREAD

**Issue by Noggin79s** [intersystems-community/developer-community#425]
I wanted to Export or Print a Post that I needed to pass along to my team-mates. When I tried to click on the Export to PDF/Print Post another page comes up and says access denied.

![image](https://user-images.githubusercontent.com/29753377/83671753-370be480-a5a3-11ea-9278-77f36f00c3da.png)

**Comment by lelikone** [comment]
Hello .
Error fixed, check if all is well, close the task.

**Comment by Noggin79s** [comment]
Yes this can be closed. I verified it worked this morning.
