### ISSUE TITLE
Validate post text/title on a client side

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#426]
Currently presence of certain characters causes this error:
```
User-uid: 

Location: https://community.intersystems.com/node/477641/edit
Referer: https://community.intersystems.com/node/477641/edit
****************************
PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x88 [...' for column 'title' at row 1: UPDATE ...
(
    [:db_update_placeholder_3] => 😈  🤫]

)

****************************
Date and Time: 2020-06-04 04:36:46
```

But the user doesn't know what went wrong.
We need to
- Validate post title and text on a client
- If they contain invalid characters show user an alert: Forbidden character %1
- If they contain invalid characters stop post submission

**Comment by lelikone** [comment]
Hi @eduard93 
I've done a check and I'm displaying an error message to the user.

**Comment by eduard93** [comment]
Please change the error message from `You can't use in the title of an emoji post.` to `Post title cannot contain emojis.`

**Comment by lelikone** [comment]
@eduard93 corrected text

**Comment by eduard93** [comment]
Thanks!
