### ISSUE TITLE
Some accepted replies are missed

### ISSUE THREAD

**Issue by adaptun** [intersystems-community/developer-community#431]
On this page [1] my reply is marked as accepted.

However when I open list of my accepted replies [2], that reply is not listed. Notice -- last accepted is of May, 20.

I expect to see it there

[1] https://community.intersystems.com/post/https-config-error-xmlreader#comment-125461
[2] https://community.intersystems.com/user/9906/comments?filter=accepted

**Comment by lelikone** [comment]
@adaptun 
Hi Alexander!
Thank you for finding that mistake.
I've finalized the code, now you can see all the answers you've accepted.

**Comment by adaptun** [comment]
Thank you! It's good now.
