### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS error

### ISSUE THREAD

**Issue by miniclub** [intersystems-community/developer-community#435]
#### Describe the problem you're observing:
Hi everyone!

When I clicked the below article, ERR_TOO_MANY_REDIRECTS error was displayed.

https://jp.community.intersystems.com/post/vismocxcach%C3%A9-direct%E3%82%92%E5%88%A9%E7%94%A8%E3%81%97%E3%81%9F%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92iris%E3%81%AB%E7%A7%BB%E8%A1%8C%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95

The screenshot is the below.
![redirect_error](https://user-images.githubusercontent.com/13766949/86335601-adc2fd00-bc89-11ea-8b73-c83ba4d75b38.jpg)

Regards,

Toshihiko Minamoto

**Comment by lelikone** [comment]
@miniclub 
Hi Toshihiko!
I fixed the mistake. Check it out, please.

**Comment by miniclub** [comment]
I checked that it has been fixed.
Thank you for the quick response.
