### ISSUE TITLE
Tag View page is empty when not logged in

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#45]
To reproduce:

1. Visit https://community.intersystems.com from a browser that's not logged in to DC
2. From the "COMMUNITY" dropdown menu choose "TAG VIEW"
3. Main area of page is blank

**Comment by evshvarov** [comment]
@gjsjohnmurray, could you please check?

**Comment by gjsjohnmurray** [comment]
Menu structure seems to have changed since this report, but from a browser that isn't logged in the View All Tags option on the Tags menu now shows a page displaying the tags. Closing this issue.
