### ISSUE TITLE
Link to anchor doesn't work

### ISSUE THREAD

**Issue by miniclub** [intersystems-community/developer-community#452]
A colleague created a link to an anchor in a article (https://jp.community.intersystems.com/node/480106) using the below dialog
![image](https://user-images.githubusercontent.com/13766949/89167021-d5252680-d5b5-11ea-8d96-5c4bd378dbf9.png)

After that she clicked on the link, it didn't jump to the anchor, but it displayed blank page (url: about:blank#blocked)
I checked the URL of the link, the URL was "https://#video1".
Is it possibile to remove "https://" from the link?

Regards

**Comment by lelikone** [comment]
@miniclub 
Hello.
I corrected that mistake. It's got to be right now.

**Comment by miniclub** [comment]
Thank you for the support.
When I double-clicked the link, the anchor was displayed on another tab of the browser.
Is it possible to jump to the anchor in the same page?

Regards,

**Comment by lelikone** [comment]
Hello!
I've rewritten the code to work with anchors, now they work by one click. If everything works fine now, please close the task

**Comment by miniclub** [comment]
Today, I checked that the links work correctly.
Thank you for the support!
