### ISSUE TITLE
Different number of accepted replies

### ISSUE THREAD

**Issue by adaptun** [intersystems-community/developer-community#456]
Hi. 

Looking at this page
https://community.intersystems.com/user/9906/comments?filter=accepted I see six pages. Each has 10 replies. And 6th page has 1 reply. That makes me think that I got 51 accepted replies.

However, following page shows 50 accepted answers for me:
https://community.intersystems.com/members?filter=accepted

I guess one of these pages is wrong.

Can you please check.

**Comment by lelikone** [comment]
@adaptun 
Hello. I checked your task and made some changes in the code.
You now have 52 accepded answers.
But the list of comments will still show 51 answers as one question has been unpublish. And it cannot be displayed in the list of comments.
You can close this task. There will be another task for further work.

**Comment by lelikone** [comment]
@adaptun 
Hi Aleksander!
You republished your answer. Now your data is a match. If you're right, close the task.

**Comment by adaptun** [comment]
Thank you!
