### ISSUE TITLE
SVG Support

### ISSUE THREAD

**Issue by yurimarx** [intersystems-community/developer-community#461]
Post editor and your upload or image link does not support SVG files. SVG files are the best option to create responsive images to the post and interactive images, that can be important to create rich interaction with users.  

I suggest you to install svg support in your drupal (drupal extensions) portal to allow upload, link and render svg files in the posts.

**Comment by lelikone** [comment]
@yurimarx 
Hello!
You will now be able to attach SVG images using the button below in the screenshot
![image](https://user-images.githubusercontent.com/21163767/103122805-d7029a00-46bc-11eb-9837-04567ac09c2e.png)
