### ISSUE TITLE
Move focus to search field when clicking the search button

### ISSUE THREAD

**Issue by bdeboe** [intersystems-community/developer-community#491]
When I click the search button (magnifying glass), it opens an overlay with a search field. However, that search field is not yet in focus so I have to click it before I can start typing my search term. A tiny inconvenience that is hopefully easy to fix :-)

Using Chrome Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by evshvarov** [comment]
Thanks Benjamin!

ср, 14 окт. 2020 г. в 18:51, Benjamin De Boe <notifications@github.com>:

**Comment by lelikone** [comment]
@bdeboe 
Hello, Benjamin!
Thank you for your wish. I have added this feature.

**Comment by bdeboe** [comment]
Thanks, you're saving me entire seconds per day! :-)

**Comment by evshvarov** [comment]
Thanks, @lelikone!
