### ISSUE TITLE
Untranslated string on jp.community.intersystems.com

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#492]
On the Subscriptions section of user's Profile page.

![image](https://user-images.githubusercontent.com/6726799/96416355-d561b500-11e7-11eb-8360-a225b9df1a8d.png)

**Comment by lelikone** [comment]
@gjsjohnmurray 
Hello!
Thank you! I have connected the translation.

**Comment by gjsjohnmurray** [comment]
Thanks. Verified that it's no longer showing English.
