### ISSUE TITLE
Members links does not work on members page

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#496]
On mobile versions, it is not possible to click open any member from the members page
It happens because of paginator which is just covers all the members
![image](https://user-images.githubusercontent.com/1212251/97265747-3583d700-1838-11eb-8ca5-765271af0cd4.png)

**Comment by lelikone** [comment]
Hello @daimor 
Thank you for finding this error. I made some changes. Is there this error now?

**Comment by daimor** [comment]
Great, it works now
