### ISSUE TITLE
Unread notifications

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#497]
Sometimes post/comments unread notifications are superfluous:
- 0 comments
- User added comment himself -> still shows as "Unread" notification

![image](https://user-images.githubusercontent.com/5127457/97270723-ab8c3c00-1840-11eb-9327-41ded487b917.png)

**Comment by lelikone** [comment]
@eduard93 Thank you. I made a change. If it happens again, please let me know.
