### ISSUE TITLE
Autoremove empty space in post

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#5]
It would be good if when saving post, empty space at the and of the post will be automatically removed.

**Comment by lelikone** [comment]
Specify, please. This emptiness itself is created, or the user enters the void and it should be cleaned at the end of the message?

**Comment by daimor** [comment]
It is created by users, they just enter new lines. Yes, it should be cleaned at the end of the message, after saving.

**Comment by lelikone** [comment]
Also I realized cleaning of empty lines for comments
