### ISSUE TITLE
Poll "abstain" option leads to browser hang

### ISSUE THREAD

**Issue by bdeboe** [intersystems-community/developer-community#507]
I created a poll as part of a discussion thread [here](https://community.intersystems.com/post/accent-sensitivity-and-other-internationalization-issues). When I tried to click "abstain" in order not to cast a vote myself (and bias those precious democratic results ;-) ), the page hangs and eventually returns a `RESULT_CODE_HUNG` error code on Chrome Version 86.0.4240.183 (Official Build) (64-bit)

**Comment by lelikone** [comment]
@bdeboe 
Hello.Thank you for finding the error. I received it too.

**Comment by bdeboe** [comment]
FWIW, the abstain option worked for me today. Not sure if you pushed a fix or whether some other bit of context changed that made it pass this time.

**Comment by lelikone** [comment]
I have made changes in some confectionary codes. I don't write about the result, as I do tests to exclude such a problem in the future.

**Comment by lelikone** [comment]
@bdeboe 
Everything is working now, if you do not notice anymore, please close the task.

**Comment by bdeboe** [comment]
Looks good, thanks!
