### ISSUE TITLE
RSS feeds invalid

### ISSUE THREAD

**Issue by gertjanklein** [intersystems-community/developer-community#512]
#### Describe the problem you're observing:

The RSS feeds are currently invalid XML. This is most likely due to the XML declaration being preceded with a space.

This is a problem for me, because I use RSS/Thunderbird for reading the posts, and it no longer accepts the feeds.

#### Steps to reproduce, if exist:

The W3C feed validator [shows the error](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fcommunity.intersystems.com%2Ftags%2Fintersystems%2520official%2Ffeed).

Downloading the XML from the feed URL and opening it in Notepad++ also shows the error. Removing the space before the XML declaration appeases Notepad++'s XML parser.

**Comment by lelikone** [comment]
@gertjanklein 
Hello!
Check it now. Is your RSS/Thunderbird updated normally?

**Comment by gertjanklein** [comment]
> Check it now. Is your RSS/Thunderbird updated normally?

It is working normally again. Thanks very much!
