### ISSUE TITLE
Please include an RSS feed for all posts

### ISSUE THREAD

**Issue by gertjanklein** [intersystems-community/developer-community#513]
**Is your feature request related to a problem? Please describe.**
RSS feeds are available only for tags. I want to see most posts, so I need to subscribe to a lot of feeds. Subsequently I see a lot of duplicated posts, because people tend to use use multiple tags.

**Describe the solution you'd like**
I would like to subscribe to a feed containing **all** posts.

**Describe alternatives you've considered**
There is no real alternative, except going to the website to check if something new has been posted. Compared to using an RSS feed that does that check for me, this is really inconvenient.

**Comment by lelikone** [comment]
@gertjanklein 
Hello!
See the link below for all the new posts.
https://community.intersystems.com/rss
The button will be available on the home page when the site is redesigned.

**Comment by gertjanklein** [comment]
@lelikone Wonderful! This seems to work perfectly, thanks!
