### ISSUE TITLE
Incorrect Japanese messages on search screen

### ISSUE THREAD

**Issue by miniclub** [intersystems-community/developer-community#518]
#### Describe the problem you're observing:
I want to change the below messages that appears when the search results are not found.

(EN) Check if your spelling is correct. 
->(JP) スペルが正しいかどうかチェックしてください。
(EN) Remove quotes around phrases to search for each word individually. bike shed will often show more results than "bike shed".
-> (JP) 単語を個々に検索するため、フレーズの前後につけたダブルクオートを外してください。「自転車 置き場」は「”自転車 置き場"」よりも多くの結果が表示されます。
(EN) Consider loosening your query with OR. bike OR shed will often show more results than bike shed.
-> (JP) ORをつけることで検索条件を緩めることも考えてください。「自転車 OR 置き場」は「自転車 置き場」よりも多くの結果を表示させます。

Regards,

Toshihiko Minamoto

**Comment by lelikone** [comment]
Hello Toshihiko!
@miniclub 
Thank you for your help with the translation.
Please check now, is everything correct?

Regards, 
Aleksey

**Comment by miniclub** [comment]
Hi Aleksay,
I checked the Japanese messages.
Thank you for the quick response!
