### ISSUE TITLE
Need to convert < > to &lt; &gt; when exporting in Markdown

### ISSUE THREAD

**Issue by miniclub** [intersystems-community/developer-community#521]
#### Describe the problem you're observing:
Typically, Markdown format is used to translate articles from English to Japanese.
English articles are exported in Markdown, but some symbols in articles such as < and > are not converted to &lt; and &gt;. Therefore, when we import the translated articles, the string between the < and > will not be displayed and it's difficult to fix them.

Regards,
Toshihiko Minamoto

**Comment by lelikone** [comment]
@miniclub 
Hello!
Please write a link to the website to study this issue.

**Comment by miniclub** [comment]
Hi!

Thank you for the support.

In fact, you can find '<root_repo_dir>' in the following article.
https://community.intersystems.com/post/deploying-intersystems-iris-solution-eks-using-github-actions

But there is no '<root_repo_dir>' in the below translated article.
https://jp.community.intersystems.com/node/483551

However, in the markdown of the translated article, you can find '<root_repo_dir>'.
https://jp.community.intersystems.com/node/483551/edit

Regards,

**Comment by lelikone** [comment]
@miniclub 
Hello Toshihiko!
I changed the converter code.
Now only one tag &lt; will be saved for export; 
This will eliminate this problem, as no nonexistent html tags will be generated.
I checked on the example of the links you gave me. Everything worked out well for me.
Check now and let me know the result.

**Comment by miniclub** [comment]
@lelikone 
Hi Aleksey,
I checked that  < and > in articles are converted to &lt; and &gt; 
Thank you for the support!
