### ISSUE TITLE
Hide digests from search

### ISSUE THREAD

**Issue by adaptun** [intersystems-community/developer-community#522]
When I search for following search string "alert windows" I'm getting many community weekly digests posts in the results. Such as "Announcement: Announcement: InterSystems Developer Community March 2018 Digest". Even if I choose announcements only -- I'm getting these digests, because they have type announcement.

Feature request: be able to remove these digests from search results.

**Comment by evshvarov** [comment]
agree with this

**Comment by lelikone** [comment]
@adaptun 
Hello Alexander! 
I have made changes. Digests should not appear in the quick search at this time.

**Comment by adaptun** [comment]
Hi @lelikone .

Strange, but I still see digests.

For example, here [0], they are 5th, 8th-9th results.

[0] https://community.intersystems.com/search?search=alert+windows

**Comment by lelikone** [comment]
I must have misunderstood, I removed the digests from the quick search, what's in the site's header.

**Comment by lelikone** [comment]
@adaptun I have made changes. Please check it. Did I do everything right now?

**Comment by adaptun** [comment]
@lelikone , still if you open https://community.intersystems.com/search?search=alert+windows

you'll see that 8th and 9th results are Digests. More on second page
