### ISSUE TITLE
Change the sharing option in posts for the CN DC

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#529]
Instead of Twitter, Facebook, add sharing options to “wechat” moment and weibo. 
The "Copy link" and LinkedIn function remains.

<img width="330" alt="image" src="https://user-images.githubusercontent.com/25077319/104469702-d711fd80-55c9-11eb-8c5d-fb1f85d93aea.png">

@lelikone

**Comment by Dyubaylo97** [comment]
Make an automated generation of QR codes for WeChat. 
Example: https://juejin.cn/post/6921890174842454023

**Comment by dyubaylo97** [comment]
Design for desktop: https://www.figma.com/file/38Sqf9lMNQnb5zDl4HEG4R/Intersystems-Community?node-id=3104%3A27866

**Comment by dyubaylo97** [comment]
Design for mobile: https://www.figma.com/file/38Sqf9lMNQnb5zDl4HEG4R/Intersystems-Community?node-id=3184%3A16556
