### ISSUE TITLE
Better Code formatting

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/developer-community#533]

**Comment by Lena-Ev** [comment]
Сделать так, чтобы работала подсветка кода

**Comment by Lena-Ev** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/77621970/166423816-2c9e9a46-e709-4992-8779-25f586be558b.png">

- [ ] сделать так чтобы можно было вернуться в редактор после сохранения кода

**Comment by Lena-Ev** [comment]
- [x] по правой кнопке сделать возможность удаления кода (пример как табличка)

**Comment by Lena-Ev** [comment]
- [x] использовать субклассы
- [ ] возможность добавления/редактирования кода по энтеру по сохранению

**Comment by Lena-Ev** [comment]
- [ ] Дизайн кнопки копирования и названия кода:

https://www.figma.com/file/vfR3fvvJ38Dlz5cz0vLKzD/InterSystems-Community-_New?node-id=3472%3A8112
<img width="902" alt="image" src="https://user-images.githubusercontent.com/77621970/167794651-53a3a38b-2212-46e2-866c-de2dc7fa1e35.png">

**Comment by jakcpto** [comment]
> * [ ]  Дизайн кнопки копирования и названия кода:
> 
> https://www.figma.com/file/vfR3fvvJ38Dlz5cz0vLKzD/InterSystems-Community-_New?node-id=3472%3A8112 <img alt="image" width="902" src="https://user-images.githubusercontent.com/77621970/167794651-53a3a38b-2212-46e2-866c-de2dc7fa1e35.png">

По дизайну задачи Алексей ведь делает или нам сделать?

**Comment by lelikone** [comment]
@jakcpto Это доработки для меня

**Comment by Lena-Ev** [comment]
https://www.figma.com/file/vfR3fvvJ38Dlz5cz0vLKzD/InterSystems-Community-_New?node-id=7827%3A22784

Mobile version

**Comment by Lena-Ev** [comment]
сборсить кеш??
<img width="255" alt="image" src="https://user-images.githubusercontent.com/77621970/168539316-25145600-8bee-4216-8477-f3efd1877c8d.png">

**Comment by lelikone** [comment]
@Lena-Ev 
Код доработали, в новом варианте будет название кода, в старых статьях будет без названия языка, так как нет разделения
