### ISSUE TITLE
Add answers and accepted answers stats to members page

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#55]
Currently displayed:
![image](https://user-images.githubusercontent.com/5127457/44334037-25faed80-a479-11e8-8782-1ba203cd2df1.png)

PLease add:

- answers
- accepted answers

**Comment by evshvarov** [comment]
Also add sorting modes for Posts/Comments/Answers/Accepted/JoinedDC

**Comment by evshvarov** [comment]
Remove followers and Following from icon

**Comment by lelikone** [comment]
Also add sorting modes for Answer (all || accepted)

**Comment by evshvarov** [comment]
Done
