### ISSUE TITLE
invalid button of prefrence management in email

### ISSUE THREAD

**Issue by claire0401** [intersystems-community/developer-community#551]
@Dyubaylo97  I want to **Unsubscribe** notification letters from OpenExchange, and click"Unsubscribe from everything in one click.", but didn't work at all. 

![image](https://user-images.githubusercontent.com/78017561/105944709-d46dd880-609e-11eb-95be-9c285c5ef4a2.png)

![image](https://user-images.githubusercontent.com/78017561/105944722-dafc5000-609e-11eb-842a-3f0870bc92aa.png)

**Comment by dyubaylo97** [comment]
We are already working on this issue. We will fix it soon! 
And please don't forget to create issues for Open Exchange here: https://github.com/intersystems-community/openexchange/issues

Thank you, Claire!
