### ISSUE TITLE
Related posts (prev & next) can only be between posts written by the same user

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#555]
Everyone can link only parts of their posts (only admins can link posts from different users).
When a user tries to link his post to someone else's, this action is not allowed, a pop-up appears: 
You linked a post created by another user. You can only add your own post to this field.

**Comment by evshvarov** [comment]
What about linked posts for the contest?

ср, 3 февр. 2021 г. в 11:44, Anastasia Dyubaylo <notifications@github.com>:

**Comment by dyubaylo97** [comment]
admins can link any posts
