### ISSUE TITLE
Exchange link is broken on the mobile site

### ISSUE THREAD

**Issue by antonum** [intersystems-community/developer-community#557]
#### Describe the problem you're observing:
If a community post is associated with the exchange code, "Open exchange" button works with the desktop version of the site and is broken in mobile.

#### Steps to reproduce, if exist:
You can reproduce the problem just by shrinking the browser till it switches to the mobile version of the responsive site.

<img width="400" alt="Screen Shot 2021-02-08 at 7 26 46 AM" src="https://user-images.githubusercontent.com/13168232/107219605-4fa88600-69df-11eb-8953-bcd19401e9b7.png">
Open Exchange button points to the:

https://openexchange.intersystems.com/package/ha-iris-k8s 

<img width="300" alt="Screen Shot 2021-02-08 at 7 27 09 AM" src="https://user-images.githubusercontent.com/13168232/107220285-2a684780-69e0-11eb-9640-99ab0a97ea76.png">

**BUG** Open Exchange button points to the:
https://community.intersystems.com/post/Array

**Comment by lelikone** [comment]
@antonum 
Hello!
Thank you for finding this error.
I have corrected it. If all is well now, please close the task.
Regards,
Aleksey

**Comment by antonum** [comment]
Verified. Corrected.

Thank you!
