### ISSUE TITLE
Show moderators if a member is subject to moderation

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#56]
When a moderator looks at a member's page, indicate if that member is being moderated.

**Comment by gjsjohnmurray** [comment]
Maybe also differentiate between these two cases:

- A member who hasn't yet posted anything. This person could be a genuine member.
- A member who has had at least one post, answer or comment rejected by the moderator. This person is more likely to be a spammer.

**Comment by evshvarov** [comment]
@gjsjohnmurray could you check, please, if it works?

**Comment by gjsjohnmurray** [comment]
What should I expect to see? I just went to https://community.intersystems.com/admin/content/comment/approval where there are currently 2 unapproved comments. I clicked on the associated usernames to view their DC profiles. I didn't spot anything indicating these users are subject to moderation. Perhaps they aren't? But I also checked the profile of a colleague who hasn't posted anything: https://community.intersystems.com/user/robert-cookson

**Comment by evshvarov** [comment]
Thanks, John. That means it’s not done yet
пт, 4 янв. 2019 г. в 15:08, John Murray <notifications@github.com>:

**Comment by evshvarov** [comment]
@gjsjohnmurray , I bet this is solved now ) You see the status of every member on his page now

**Comment by gjsjohnmurray** [comment]
Great!, Thanks. Closing.
