### ISSUE TITLE
Spelling error in Members section of my Subscriptions page

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#565]
![image](https://user-images.githubusercontent.com/6726799/108684496-e0588900-74ea-11eb-82a3-f8080837adf8.png)

**Comment by lelikone** [comment]
@gjsjohnmurray 
Hello John!
Thank you for finding the spelling error. I have corrected it, if it is correct, close the task.

**Comment by gjsjohnmurray** [comment]
Confirmed fixed. Thanks.
