### ISSUE TITLE
Moderation: unreadable button

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#567]
![image](https://user-images.githubusercontent.com/6726799/108985778-53980180-7689-11eb-972f-c0c285199e42.png)

When hovering I can at least see what the button will do:

![image](https://user-images.githubusercontent.com/6726799/108985928-82ae7300-7689-11eb-8330-7ec513ba6b8f.png)

**Comment by lelikone** [comment]
@gjsjohnmurray 
Hello John!
I made it visible. Now these buttons are being redrawn by the designers and they will look different.
If you can see the text clearly now, please close the task.

**Comment by gjsjohnmurray** [comment]
:+1:

![image](https://user-images.githubusercontent.com/6726799/108999853-d2496a80-769a-11eb-8c7f-855d42d9cd26.png)
