### ISSUE TITLE
Screen cheese on New Post page

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#569]
![image](https://user-images.githubusercontent.com/6726799/109288261-845c7000-781c-11eb-98fb-05c3415bde8e.png)

**Comment by lelikone** [comment]
@gjsjohnmurray 
Hello John!
I understand this has happened in the Firefox browser. This has not happened in other browsers. Thank you for telling me about this bug. I have made small changes to take into account the peculiarities of this browser.

**Comment by gjsjohnmurray** [comment]
:+1:

![image](https://user-images.githubusercontent.com/6726799/109400734-3477c900-7942-11eb-90b4-3962f24ff34d.png)
