### ISSUE TITLE
Hide spammers from Members list

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#57]
If a member under moderation posts things that the mods reject, hide that member from the searchable member list.

**Comment by evshvarov** [comment]
Hi @gjsjohnmurray ! is it fixed?
Question: if you decide to bring member back, how do you find him? )

**Comment by gjsjohnmurray** [comment]
LGTM

As a mod I can still find banned members:
![image](https://user-images.githubusercontent.com/6726799/64127530-f67c0200-cda9-11e9-84b9-bb382f839127.png)

Closing.
