### ISSUE TITLE
Certification badges for contests

### ISSUE THREAD

**Issue by jrpereirajr** [intersystems-community/developer-community#571]
**Is your feature request related to a problem? Please describe.**
No related to a problem, just a new feature.

**Describe the solution you'd like**
I'd like to have a more fancy way to publish my achievements in community contests, something like [badges for certifications](https://github.com/intersystems-community/developer-community).

**Describe alternatives you've considered**
It's possible to link OpenExchange contest page, but I think it'd be better have a direct link to your rank position.

**Additional context**
I missed such feature while updating my LinkedIn profile. I'd like to publish my achievements in community contests.

**Comment by Lena-Ev** [comment]
Now we have app badges on the app's page, but I hear you - we will add the OEx badges to the Community profile too. 


![Image](https://user-images.githubusercontent.com/77621970/174605239-c6ecc4a5-2f2e-4243-8068-f8062e3a42f6.png)

**Comment by Lena-Ev** [comment]
@jrpereirajr we will add an extra tab for rewards of your app

Could you please let mew know how you want to share your rewards on linked in?
Just providing a link for each reward, or you would want to provide a link to the page with all the rewards?
Or maybe other way.
So we could take it in consideration when implementing


![Image](https://user-images.githubusercontent.com/77621970/178689859-32c9bc29-02d1-4a81-a11b-7423f4eed535.png)

**Comment by jrpereirajr** [comment]
Hi @Lena-Ev,

Thank you for your feedback!

I think a link to all rewards it's a good idea in order to keep things clean in linked in. 
An additional feature would be (if possible) to put in that link the amount of rewards that user achived. So, it'd be better to give to viewers an idea of the user performance on contests and keep things clear.

**Comment by Lena-Ev** [comment]
Got you!
You want to post this link just in the linked in post? Or some other way,
I am trying to understand that so to consider how to implement it better

**Comment by Lena-Ev** [comment]
@jrpereirajr 
We gathered all the award of any developer at one page:
https://openexchange.intersystems.com/user/Jos%C3%A9%20Roberto%20Pereira/hYivAh9O4bfh4fs7OYvoXRBRg?tab=rewards

When sharing - it will show how many awards you have, later we will add a respective picture with apps and awards qty.

**Comment by jrpereirajr** [comment]
Thanks @Lena-Ev!
I've updated my linkedin page adding the link in featured section:
![image](https://github.com/intersystems-community/developer-community/assets/6760817/f8796fd6-8866-442a-99be-08a5d1bcaec5)
