### ISSUE TITLE
Display fault affecting consecutive comments awaiting moderation

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#573]
![image](https://user-images.githubusercontent.com/6726799/109631098-8c2e5400-7b3d-11eb-9398-84094316f9da.png)

It looks like there's a missing break between the first and second comment, and between the second and third one.

**Comment by lelikone** [comment]
@gjsjohnmurray
Hello John!
I fixed it. If now ok, please close the task.

**Comment by gjsjohnmurray** [comment]
@lelikone it might be some time before I get consecutive comments waiting for moderation again. So I'll close it now and reopen it if I see the problem again.
