### ISSUE TITLE
Autoreplace intersystem with InterSystems

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#574]
Problem: people write _intersystem_ (any case, lacks *s* at the end)

Solution: in post text and title replace _intersystem_ with _InterSystems_ automatically.

Be careful not to replace _InterSystems_ with _InterSystemss_.

**Comment by lelikone** [comment]
@eduard93
Hello Eduard. 
I have done this, please check if everything is OK now. The title in the header and body of the post is now being corrected. I've checked a few options, it works. If you have it right too. Close the task please.
