### ISSUE TITLE
Add copy-to-clipboard button to code blocks

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/developer-community#576]
and to "without formatting blocks too.

**Comment by dyubaylo97** [comment]
icon: https://www.figma.com/file/vfR3fvvJ38Dlz5cz0vLKzD/Intersystems-Community-_New?node-id=3476%3A3513

animation: https://www.figma.com/proto/vfR3fvvJ38Dlz5cz0vLKzD/Intersystems-Community-_New?node-id=3495%3A2803&viewport=14753%2C8570%2C2.144043445587158&scaling=min-zoom&page-id=3471%3A0

when you click on the icon, the "copied" notification pops up and goes out after 300 ms

**Comment by dyubaylo97** [comment]
Please check here: https://community.intersystems.com/post/get-list-cached-queries-and-their-texts
