### ISSUE TITLE
Open Exchange: Subscribed to all applications

### ISSUE THREAD

**Issue by AndrewBartholomewVA** [intersystems-community/developer-community#577]
#### Describe the problem you're observing:
I recently cloned an application from the developer community git hub. I am now subscribed to all updates to all applications on the open exchange, and my inbox is flooded with automated emails on projects I have no interest in. 
When I log into Open Exchange, I go to my subscriptions, then applications, I see that I am subscribed to all applications. (screenshot attached). There are more than 300 apps listed and it's not reasonable to have to unsubscribe to all of them.

How can this be resolved? 

![image](https://user-images.githubusercontent.com/70662233/110351991-5f79b100-8003-11eb-947a-d22eba5c5bcb.png)

#### Steps to reproduce, if exist:

I cloned a single application, apps-rest, and my open exchange account is now subscribed to every applications.

**Comment by MakarovS96** [comment]
Hello! Activity on Github has nothing to do with OEX subscriptions. I found uncommented debug code that adds all subscriptions to users when they sign up, it shouldn't be that way. Thanks for the feedback! In the future, if you have any problems, please write here: https://github.com/intersystems-community/openexchange/issues
