### ISSUE TITLE
Where in the DC database can I get a bookmark counter?

### ISSUE THREAD

**Issue by MakarovS96** [intersystems-community/developer-community#58]
I need it to add to the analytic.

**Comment by MakarovS96** [comment]
I have tried to get flags_count(save_node), but it hasn't matched the number of bookmarks in the Post.

**Comment by eduard93** [comment]
Example:
```
SELECT Count(*)
FROM subscriptions
WHERE field = 'nid' and value=448191
```

Post: https://community.intersystems.com/node/448191/

**Comment by eduard93** [comment]
Favorites. not subscriptions

**Comment by eduard93** [comment]
No idea.

**Comment by MakarovS96** [comment]
Me too.

**Comment by lelikone** [comment]
@MakarovS96
SELECT COUNT(*) FROM {flagging}  WHERE `fid` = :fid AND `uid` = :uid and `entity_type`=:type"

 ':fid' =>21,
    ':uid' => user id,
	':type' => 'node',

**Comment by MakarovS96** [comment]
It doesn't work. @lelikone why do you use :fid equals "21"?
We didn't have the flag with id 21. If I use fid 2, I get incorrect values.
For example:   
[This](https://community.intersystems.com/post/atelier-and-studio) post have four bookmarks.
But this query return nothing.
```sql
SELECT COUNT(*) as cnt, entity_id
FROM flagging
WHERE fid = 2 and entity_type='node'
GROUP BY entity_id
having entity_id = 450311
```

**Comment by lelikone** [comment]
fid only 21

**Comment by MakarovS96** [comment]
![image](https://user-images.githubusercontent.com/19629483/45343328-e8a2ff00-b5e3-11e8-8bd9-1db80f7582c5.png)
![image](https://user-images.githubusercontent.com/19629483/45343337-ee98e000-b5e3-11e8-92f1-a85e55dc4b0a.png)
It's all "fid" that we have.

**Comment by lelikone** [comment]
![image](https://user-images.githubusercontent.com/21163767/45343862-ae7e3100-b5d4-11e8-8330-37a93aaaedbf.png)

**Comment by MakarovS96** [comment]
@lelikone wow!
@eduard93 Maybe we don't update tables "flags" and "flagging" in database mirror?

**Comment by lelikone** [comment]
Capability not update. This is an extract from the database on the local computer on June 26, on the production server of this data will be more.

**Comment by lelikone** [comment]
@MakarovS96
Please select
SELECT * FROM `flag`

**Comment by MakarovS96** [comment]
@lelikone thanks! I will ask @eduard93 to configure update these tables.

**Comment by MakarovS96** [comment]
@lelikone if you need. This result of query `SELECT * FROM flag`:
![image](https://user-images.githubusercontent.com/19629483/45346057-759d8680-b5eb-11e8-8a6a-7e538409460f.png)

**Comment by lelikone** [comment]
@MakarovS96 That's right, outdated data, missing three more flags
