### ISSUE TITLE
List of release announcements for InterSystems products

### ISSUE THREAD

**Issue by miniclub** [intersystems-community/developer-community#599]
**Is your feature request related to a problem? Please describe.**
Hi all,
Customer supports in Japan are sometimes asked by their customers which version of InterSystems products was released and when, so we need a list that can be easily viewed.

**Describe the solution you'd like**
It would be great if you could create a page ( filter? ) that shows annnouncements which have 'InterSystems-official' and 'release' tags.

Thanks in advance,

**Comment by dyubaylo97** [comment]
Hello there,

First of all, it should be noted that all official releases are published with the [InterSystems Official tag](https://community.intersystems.com/tags/intersystems-official). 

The [Release tag](https://community.intersystems.com/tags/release) is not only used for official announcements, it's open to all DC members. This tag includes announcements on releases of a new version of software, package, addon, system, service – for example, you can see regular app releases there, not only official releases/announcements.

There are several ways to keep track of all official announcements (releases):

1. Follow (subscribe) to the InterSystems Official tag:
- you will receive email notifications about every new post with this tag
- all posts with this tag will go to the "My feed" section
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/25077319/114543813-616a0c00-9c62-11eb-99f0-a748365dd593.png">

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/25077319/114543751-48615b00-9c62-11eb-8077-b02d8b38f3e7.png">

2. Go to the tag and filter posts by publication date, then you will see all the latest releases at the top of the posts feed.
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/25077319/114543304-b3f6f880-9c61-11eb-9179-2e194afb4692.png">

Hope this helps! Please let me know if you still have any questions.

**Comment by dyubaylo97** [comment]
![image](https://user-images.githubusercontent.com/25077319/115036200-f7f23380-9ed5-11eb-9550-7c9415ebd7ec.png)

Posts will be sorted by tags:
ISC Off and Releases tags --> to the Releases section
ISC Off and Alerts tags --> to the Alerts section
All section for all announcements.

@lelikone

**Comment by dyubaylo97** [comment]
Please check: 
https://community.intersystems.com/tags/intersystems-official?sort=creation&period=releases
