### ISSUE TITLE
Action Icons on answer without titles.

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#6]

**Comment by evshvarov** [comment]
Are we using answers without title frequently?

**Comment by daimor** [comment]
![image](https://user-images.githubusercontent.com/1212251/36075078-8d24f502-0f49-11e8-84ef-35e6c7a2c57a.png)
This arrow should have the title on hover. In comments it is works, but not for answers

**Comment by daimor** [comment]
BTW: other icons, also with no title.

**Comment by evshvarov** [comment]
Internal task DCE-355
