### ISSUE TITLE
Preview of comment displays stray ` [comment:flag-bookmark-comments-count]` text

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#602]
![image](https://user-images.githubusercontent.com/6726799/115133364-86ae9f80-9fff-11eb-9389-e4fd7107c8ff.png)

**Comment by dyubaylo97** [comment]
Disable the entire bottom part with icons in the comment preview. @lelikone 

<img width="918" alt="image" src="https://user-images.githubusercontent.com/25077319/115205332-1fc5df00-a102-11eb-988b-dcc5b293e93e.png">

**Comment by lelikone** [comment]
@gjsjohnmurray @Dyubaylo97 
Hello!
I disabled the entire bottom part with icons in the comment preview.
If this is correct. Please close the task.

**Comment by dyubaylo97** [comment]
@lelikone great! thank you!
@gjsjohnmurray thanks for noticing it :)
