### ISSUE TITLE
Moderator unable to save edit of a post that has a link to a previous article

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#611]
#### Describe the problem you're observing:

As moderator,cannot save an edit of the body of a post by another member in which there is a value in the Previous Post field.

#### Steps to reproduce, if exist:

1. Be a moderator.
2. Go to a post that has a Previous Post link, for example https://community.intersystems.com/post/online-meetup-intersystems-developer-tools-contest-winners
3. Make a change to the body of the post.
4. Try to save it.

`Error: You linked a post created by another user. You can only add your own post to this field.`

**Comment by lelikone** [comment]
@gjsjohnmurray 
Hello.
I have now allowed access for moderators.
Please check.

**Comment by gjsjohnmurray** [comment]
@lelikone I re-tested by trying to edit that same post, but I got the same error when saving.

**Comment by lelikone** [comment]
@gjsjohnmurray 
Please send me a screenshot and the address of the post

**Comment by lelikone** [comment]
@gjsjohnmurray 
Try again

**Comment by gjsjohnmurray** [comment]
That worked. Closing.
