### ISSUE TITLE
Limit translate post to 1 or 2 daily

### ISSUE THREAD

**Issue by KurroLopez** [intersystems-community/developer-community#615]
We are able to translate post, question or other publication from a community to other language, it's a good idea to spread the knowledge to other community and break the wall of the language for other users.

But is not normal that one user create more than 10 translates for random posts in one day. I don't think if it's a good practices. It looks a "collect global master points", maybe I'm wrong but it is looks

I propose limit a 1 or 2 translate daily for all users, except if the translate is for a owner post (maybe I create a serie of posts and I want to spread from my language to English community)

**Comment by dyubaylo97** [comment]
Hi Kurro,

Thanks for the issue! For now we have decided to unpublish these translated questions and will contact the authors asking them to publish the content in portions: 1 post per day. We hope that this will help regulate the process of publishing translations. If not, we will put them on moderation forever.

Therefore, for now, we will not introduce technical restrictions on the publication of translations on our website. However, perhaps we will return to this issue ;)
