### ISSUE TITLE
Require Followers to be accepted

### ISSUE THREAD

**Issue by rcemper** [intersystems-community/developer-community#617]
I dislike to be followed by anyone without any chance to escape or avoid this.
I want a feature to approve / disapprove if someone is following me.
Actually I just get mail "mahmoud neverheardbefore" is following you. BINGO!
And I have to accept and can't disagree ! 
In Facebook or Twitter or ...  I have the chance to accept "friends"

**Comment by dyubaylo97** [comment]
Robert,

Our site is not a social network, Developer Community is a technical **open** forum. We do not have private accounts and private published content. Any user can see your activities and published posts - they don't have to follow you for this. Therefore, we do not consider it necessary to add such an option, we are a site open to all users. 

If any user commits suspicious activity related to your account, you can inform us about it. Then, our moderators can block this user (like DC MOD, you can do it yourself). But if any user does not violate any rules of [DC Code Of Conduct](https://community.intersystems.com/post/intersystems-developer-community-code-conduct), we cannot deprive him / her of the opportunity to follow anyone.

We hope for your understanding! Thanks!
