### ISSUE TITLE
Introduce Community Analytics to DC: iframe/articles/week/month/performance

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/developer-community#62]
https://analytics.community.intersystems.com/dswpub/index.html#!/d/Authors/AuthorsPostings.dashboard?ns=COMMUNITYPUBLIC&FILTERS=TARGET:*;FILTER:%5BDateDimension%5D.%5BH1%5D.%5BYear%5D.%26%5BNOW%5D~%5BPublishedDimension%5D.%5BH1%5D.%5BYear%5D.%26%5BNOW%5D~%5BAuthor%5D.%5BH1%5D.%5BAuthor%5D.%7B%26%5BJohn%20Murray%5D%2C%26%5BMurray%20Oldfield%5D%7D~%5BPostType%5D.%5BH1%5D.%5BPostType%5D.%26%5BArticle%5D

**Comment by lelikone** [comment]
<iframe style="border: none" src="https://analytics.community.intersystems.com/dswpub/index.html#!/d/Authors/AuthorsPostings.dashboard?ns=COMMUNITYPUBLIC&FILTERS=TARGET:*;FILTER:%5BDateDimension%5D.%5BH1%5D.%5BYear%5D.%26%5BNOW%5D~%5BPublishedDimension%5D.%5BH1%5D.%5BYear%5D.%26%5B2018%5D~%5BName%5D.%5BH1%5D.%5BName%5D.%26%5BAtelier%20security%20quirk%5D~%5BPostType%5D.%5BH1%5D.%5BPostType%5D.%26%5BArticle%5D&widget=0&height=723" width="1272" height="723" ></iframe>

**Comment by evshvarov** [comment]
Done
