### ISSUE TITLE
wrong link in mail "Thank you for submitting the comment"

### ISSUE THREAD

**Issue by cambid** [intersystems-community/developer-community#628]
#### Describe the problem you're observing:
The mail with the subject "Thank you for submitting the comment" has a link to https://github.com/intersystems-community/issues. This link isn't working and AFAIS the name of the repo is missing in the URL.

#### Steps to reproduce, if exist:
* Create a new comment.
* Wait for the mail "Thank you for submitting the comment" in the inbox.
* Open the link in it.

**Comment by lelikone** [comment]
@cambid 
Hello Jan.
Thank you for your help.
Correct link below, replaced it in the email.
https://github.com/intersystems-community/developer-community/issues/
