### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by miniclub** [intersystems-community/developer-community#640]
#### Describe the problem you're observing:
The link 'Download InterSystems IRIS' on the Japanese page (https://jp.community.intersystems.com) is wrong, so when you click the link, you will see '403 Forbidden'.

#### Steps to reproduce, if exist:
Access to 'https://jp.community.intersystems.com' from your browser.
Click the link 'Download InterSystems IRIS' in the left side of the page.
It shows Forbidden page.

The below link is right.
https://download.intersystems.com/download/login.csp?lang=jp

Regards,
Toshihiko Minamoto

**Comment by lelikone** [comment]
@miniclub 
Hello. We have corrected the link to temporary. All links will be rechecked and translated to Japanese. Thank you for your comments.
