### ISSUE TITLE
Adding a `<!--break-->` tag hides everything after that

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#648]
#### Describe the problem you're observing:

Adding a `<!--break-->` tag hides everything after that

#### Steps to reproduce, if exist:

![image](https://user-images.githubusercontent.com/5127457/122279801-22ba3180-cef1-11eb-83fc-82dbf6138e85.png)

![image](https://user-images.githubusercontent.com/5127457/122279808-26e64f00-cef1-11eb-8a49-c782cfd9f78e.png)

Sample post: https://community.intersystems.com/node/498101

**Comment by lelikone** [comment]
@eduard93 
Hello Edward.
I have made changes to the site, please check if everything is working correctly now? If everything is fine close the task.

**Comment by eduard93** [comment]
Works OK.
