### ISSUE TITLE
Rate-limit posts from members who are on moderation

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#652]
We just had a spammer (on moderation) submit an identical comment to a post about ten times in quick succession. I banned him and marked all the comments as spam. But maybe the DC platform needs to rate-limit posts, especially from people who are on moderation. Perhaps no more than 2 per hour?

**Comment by Lena-Ev** [comment]
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/77621970/164233996-67b5482b-5768-4a98-8ddc-fe4d934d763e.png">

![image](https://user-images.githubusercontent.com/77621970/164234105-8d2ab613-db71-44da-8853-81632d9a700e.png)

Предлагаю сделать тултип на этот шилльдик on moderation:

As it is your first comment on our website, it is visible only for you until the moderator accepts it

<img width="945" alt="image" src="https://user-images.githubusercontent.com/77621970/164234299-1dd8c74f-4459-4941-9bc3-ff4b7fb97325.png">

**Comment by Lena-Ev** [comment]
the bug has been fixed.
tested - no more duplicates sent out
