### ISSUE TITLE
Trying to disable subscription throws "Error: An illegal choice has been detected. Please contact the site administrator."

### ISSUE THREAD

**Issue by isc-naaron** [intersystems-community/developer-community#658]
#### Describe the problem you're observing:

I am unable to disable subscriptions. I have tried logging out and back in, but no luck. Whenever I disable (uncheck) a subscription and hit the 'Save settings' button , I see a red banner at the top of the page saying "Error: An illegal choice has been detected. Please contact the site administrator." See image below:

![Screen Shot 2021-07-22 at 8 49 59 AM](https://user-images.githubusercontent.com/15818272/126641704-bb951084-6e82-4005-b850-8cd1a6e588b3.png)

#### Steps to reproduce, if exist:

1. Select profile image in the top right of the DC and select My Account
2. Select Subscriptions on the left
3. Uncheck 'Weekly posts digest' and 'Save settings'
4. The error message will appear, and the box remains unchecked. But reloading the Subscriptions page shows that the box is still checked
5. At the bottom of the Subscriptions page, select the 'Tags' tab
6. Uncheck a 'Follow tag' or 'Follow comments' box and 'Save settings'
7. The error message appears at the top and the 'Follow' boxes are still checked

**Comment by lelikone** [comment]
@isc-naaron 
Hello Nicole!
Please give me a link to your profile so I can see more details.
I cannot reproduce this error on my profiles

**Comment by dyubaylo97** [comment]
Here is Nicole's profile: https://community.intersystems.com/user/nicole-aaron

**Comment by isc-naaron** [comment]
Any updates on this? I'm still seeing the same behavior.

**Comment by dyubaylo97** [comment]
Hi Nicole,
We are trying to reproduce this bug, but unfortunately with no success. We can set up your subscriptions manually for now - what do you think? Please let us know your preference. 
And we will continue to work on this bug further.

Thank you for your patience!

**Comment by lelikone** [comment]
@isc-naaron 
Hello.
Try to make these changes now

**Comment by isc-naaron** [comment]
@lelikone It works now, thanks so much! Closing this out.
