### ISSUE TITLE
Dynamic page refresh when adding a new or updating a comment

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#659]

**Comment by dyubaylo97** [comment]
intersystems-community/dc-planning#10

**Comment by Lena-Ev** [comment]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/77621970/163363899-d3b30b53-af8b-4ccb-b845-841131d8d67f.png">

**Comment by lelikone** [comment]
@Dyubaylo97 Подскажите что не так реализовано?
