### ISSUE TITLE
JP, PT DC filter translation

### ISSUE THREAD

**Issue by irinapodmazko** [intersystems-community/developer-community#661]
Tag page 
https://pt.community.intersystems.com/tagsclouds

![image](https://user-images.githubusercontent.com/44035497/127011026-30e6f617-911e-4eea-84e1-8325691d54b2.png)

Translation https://docs.google.com/spreadsheets/d/1H88leAnK2rqknaySwm2Qlr3CvD7dYerm/edit#gid=1611353869

**Comment by CM-DC-ES** [comment]
The translation into Spanish it is just partially done. Could you please finish it? I have added the Spanish translation of the words in the google sheet. Thanks!
![imagen](https://user-images.githubusercontent.com/50864675/127278976-c9616202-db93-48b5-915b-19c7a9eee4a1.png)

**Comment by dyubaylo97** [comment]
Hi Esther, please don't forget to check the labels of the issue.

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/25077319/127308945-a3711c39-11b7-4ebf-98cf-d79e79173e6c.png">

And thank you for noticing this! Your issues encourage us to check all the regional sites ;)

**Comment by lelikone** [comment]
translation done
