### ISSUE TITLE
ES DC: Change the order on the main menu

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#662]
Could you please change the order of the tags "Etiquetas" and "Debates" under "Publicaciones" on the main menu?
I would like to have "Etiquetas" below "Debates", like on the EN DC.
Thanks! 
![imagen](https://user-images.githubusercontent.com/50864675/127286964-a96e8fc1-12c0-48e5-82e1-94b9b2477a4c.png)

**Comment by lelikone** [comment]
I changed it. Please check

**Comment by CM-DC-ES** [comment]
Thanks!
