### ISSUE TITLE
ES DC - Filtering the tags by name

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#663]
When I filter the tags by name on the ES DC, the result is not correct, please check:
![imagen](https://user-images.githubusercontent.com/50864675/127463804-3a16548e-3daf-48ff-9848-9b6b519a2b44.png)

For example, the tag "Feedback sobre la DC" appears before "Developer Community Official", which is obviously not correct. I think that the filter shows the tags ordered by their name in English, although they are translated into Spanish.

So just wondering if you could fix this for me?

Thanks!

**Comment by dyubaylo97** [comment]
Hi Esther, 
Alexey will deal with this a little later - the task is not easy, but we will definitely fix it. Thanks for noticing!

**Comment by CM-DC-ES** [comment]
Great! Thanks! :D

**Comment by lelikone** [comment]
@CM-DC-ES 
Hello Esther,
I made the changes, check if everything is correct, close the task please

**Comment by CM-DC-ES** [comment]
Hi Aleksey,

when I access the area "Etiquetas" (Tags) on the DC in Spanish I see all the tags in English, am I right?

[https://es.community.intersystems.com/tagsclouds](https://es.community.intersystems.com/tagsclouds)

Thanks
Esther

**Comment by dyubaylo97** [comment]
Hi Esther,
The point here is that some tags have no translation. We have created the [new issue](https://github.com/intersystems-community/developer-community/issues/670) and will check all the tags for translation. Then we will update them on the site and everything will be correct.

**Comment by CM-DC-ES** [comment]
Hi Anastasia,

now I see your answer, sorry! I was saying that ALL the tags on the DC in Spanish appear in English. So not just some tags, but all of them. It has to be a bug or a wrong redirection, please check:

https://es.community.intersystems.com/tagsclouds

Thanks!
Esther

**Comment by lelikone** [comment]
@CM-DC-ES 
Hello  Esther,
Can you describe the problem in more detail, as I do not see the error.

**Comment by CM-DC-ES** [comment]
Hi!
When you access [https://es.community.intersystems.com/tagsclouds](https://es.community.intersystems.com/tagsclouds) you see all the tags in English. There is no one in Spanish. And that's not correct, since some tags have been translated.

For example: "Other" should be "Otro", "Online learning" should be "Formación online", "Documentation" is "Documentación"...
![imagen](https://user-images.githubusercontent.com/50864675/133624111-fc4b1c2d-35ba-4903-a94f-bd165d2f2e6b.png)

I sent you a spreadsheet with all the translations some months ago. Please check: [Etiquetas_EN-ES.xlsx](https://github.com/intersystems-community/developer-community/files/7178258/Etiquetas_EN-ES.xlsx)

**Comment by lelikone** [comment]
@CM-DC-ES 
![image](https://user-images.githubusercontent.com/21163767/133627135-b2bb402c-c95d-4119-8dc4-d8afeac29fbb.png)
Right now it looks like this

**Comment by CM-DC-ES** [comment]
I dont see that, Aleksey. I access [https://es.community.intersystems.com/tagsclouds](https://es.community.intersystems.com/tagsclouds) and I see all the tags in English.
Look at my screenshot:
![imagen](https://user-images.githubusercontent.com/50864675/133627709-e9cd52f4-9e0d-4465-bfcb-c976ca7663ea.png)

**Comment by lelikone** [comment]
@CM-DC-ES 
Check now please

**Comment by CM-DC-ES** [comment]
Fixed!! Thanks!! :D :D
