### ISSUE TITLE
ES DC - Filter translation

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#664]
Sorry for this, but I have noticed that one of my translations of the filters on the Tags section wasn't so correct:
![imagen](https://user-images.githubusercontent.com/50864675/127469092-b36191d3-e7e4-40ef-a031-2645510519a0.png)

So could you please change again the translation? Instead of "Por novedad" it is better "Por actualización".

Thanks!
ES

**Comment by lelikone** [comment]
Please heck it

**Comment by CM-DC-ES** [comment]
Great, thanks!
