### ISSUE TITLE
ES DC - Tags missing 

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#665]
Checking the tags on the Spanish DC, I have noticed that there are some tags missing on the drop-down menu when writing an article.
For example, the tag "CaretDev" does exit in the list of tags:
![Captura de pantalla 2021-08-04 a las 11 54 57](https://user-images.githubusercontent.com/50864675/128161536-adb0c502-c626-4653-852f-68fe77f532bc.png)
But when you edit an article, for example, and want to fill the Tags field, that tag it is not shown:
![Captura de pantalla 2021-08-04 a las 11 47 28](https://user-images.githubusercontent.com/50864675/128160949-611038c3-bd7f-4775-b952-0f6a8b107a99.png)
So now I don't know if all the tags in the list of tags are available on the Tags field or there are more tags missing. Could you please check it?
Thanks!
Esther

**Comment by lelikone** [comment]
@CM-DC-ES 
Hello. Not all tags are available when creating an article. Some tags can set a limited number of participants. the tag "CaretDev" refers to such.

**Comment by CM-DC-ES** [comment]
ok, thanks Aleksey!
