### ISSUE TITLE
Translate Partner Directory tag

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#666]
https://community.intersystems.com/tags/partner-directory

**Comment by irinapodmazko** [comment]
Translation is ready
https://docs.google.com/spreadsheets/d/17gBHaSOKaepMjB2AkEDvvtuREpdR-zC2/edit#gid=809405193

**Comment by CM-DC-ES** [comment]
Hi! Could you please change the tag from "Directorio de socios" to "Directorio de partners"? I think that the word "partner" is widely used here in the business environment.
Thanks!
