### ISSUE TITLE
Color on buttons in pool

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#667]
Buttons are just white on white until hovered (Vote)
![image](https://user-images.githubusercontent.com/1212251/129527117-4d51b3f2-c951-42fe-a72d-7ae4e4955a6d.png)

**Comment by lelikone** [comment]
@daimor 
Hello Dmitry.
Thank you!
Please check now

**Comment by daimor** [comment]
![image](https://user-images.githubusercontent.com/1212251/129534298-750816dc-ec2a-492a-b310-de04d42cd1de.png)
ok, now
