### ISSUE TITLE
The download link for InterSystems IRIS is currently broken.

### ISSUE THREAD

**Issue by bmochock** [intersystems-community/developer-community#669]
#### Describe the problem you're observing:
The download link for InterSystems IRIS isn't working. Following it leads to an error page.

#### Steps to reproduce, if exist:
1. Log in and navigate to [the developer community page for InterSystems IRIS](https://community.intersystems.com/tags/intersystems-iris).
2. Follow the [link to download IRIS](https://download.intersystems.com/download/login.csp). 
3. You'll see an error that indicates the site can't be reached.

**Comment by dyubaylo97** [comment]
Hi Bren,
We are already working to fix it. Please stay tuned for updates in [your post](https://community.intersystems.com/post/link-download-intersystems-iris-down#comment-164141) on the community. Thank you!
