### ISSUE TITLE
Many duplicates for the post during publication

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#679]
#### Describe the problem you're observing:
New users, usually on moderation, may create multiple new posts with exactly the same topic and content just within a minute.
#### Steps to reproduce, if exist:
Create a new post, fill it and press publish multiple times.

**Comment by gjsjohnmurray** [comment]
Do moderated members get notified that their post won't appear immediately? If not, perhaps this should be done.

**Comment by gjsjohnmurray** [comment]
#652 may also be relevant.
