### ISSUE TITLE
Users cannot add the same links to the Previous and Next post when creating a post

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#701]
When a user tries to save a post, a popup appears:
"The same post cannot be added to both Next and Previous fields."

**Comment by dyubaylo97** [comment]
Change pop-up to "The same post cannot be added to both Next and Previous fields."

**Comment by Lena-Ev** [comment]
проверить, правильная ли фраза выводится при ошибке, когда ссылка одна и та же


<img width="1204" alt="image" src="https://user-images.githubusercontent.com/77621970/162738459-9da973f6-54f1-4f8d-a4f1-1d7ad0d8ddc3.png">
