### ISSUE TITLE
ES DC - Not able to click on the results of a search

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#703]
When you search for a phrase (not a title) in the Spanish Dev Community, you can't see the title or a preview of the results, and you can't click on any of the result. So now those kind of searchs are useless. Just wondering if you could fix it? It doesn't happen when searching for phrases in the English Dev Community.

![imagen](https://user-images.githubusercontent.com/50864675/145789528-1430879f-f920-4e8b-aa9e-360ca529216a.png)

Thanks!
Esther

**Comment by lelikone** [comment]
@CM-DC-ES 
Hello Esther!
Please check now.

**Comment by CM-DC-ES** [comment]
Great! Thanks! :D
