### ISSUE TITLE
Убрать тултипы с гиперссылок и переименовать копи на никнейме пользователя

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#709]
The issue to remove / edit some tooltips on the DC site

**Comment by dyubaylo97** [comment]
![image](https://user-images.githubusercontent.com/25077319/145976382-86a2b4cd-c638-4ae1-99c3-75ea5782ca30.jpeg)

**Comment by lelikone** [comment]
@Dyubaylo97 Ok

**Comment by dyubaylo97** [comment]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/25077319/147473416-6a7c6f14-693c-4f1b-926e-49afe97ce6f0.png">


Edit
Remove
Delete
Convert comment to question

**Comment by dyubaylo97** [comment]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/25077319/148643671-a00cc2d9-2c3d-4b36-8cc9-de5d3aae4abd.png">

**Comment by dyubaylo97** [comment]
- [x] todo
- [x] <img width="337" alt="image" src="https://user-images.githubusercontent.com/25077319/152369720-5c6cdefc-27c6-43fa-a35f-f9f59c459bd0.png">

Copy to clipboard --> Copy

**Comment by dyubaylo97** [comment]
- [ ] todo

<img width="966" alt="image" src="https://user-images.githubusercontent.com/25077319/152773776-e25f7146-5e85-4334-94a7-9afe67b84bd6.png">

**Comment by dyubaylo97** [comment]
<img width="442" alt="image" src="https://user-images.githubusercontent.com/25077319/154123720-6209abde-2388-463d-b478-e18bb420137f.png">
<img width="197" alt="image" src="https://user-images.githubusercontent.com/25077319/154123779-14a43285-dff0-4b90-9c56-6233ab194bac.png">

**Comment by dyubaylo97** [comment]
- [ ] todo

<img width="817" alt="image" src="https://user-images.githubusercontent.com/25077319/161971621-94beed2b-16e0-499e-9322-437b65d77240.png">

https://community.intersystems.com/post/introducing-intersystems-ideas
