### ISSUE TITLE
Direct link to an answer should go to a corresponding post 

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#71]
for instance: 
link from need moderation mail
https://community.intersystems.com/node/453031
opens new URL
https://community.intersystems.com/question452961/answer453031
and by this URL visible only this particular answer, without original question.
expected URL is
https://community.intersystems.com/post/creating-fhir-server-using-existing-data-source##node-453031
complete post with the link to answer

**Comment by evshvarov** [comment]
@daimor close it if works?

**Comment by evshvarov** [comment]
@daimor update
