### ISSUE TITLE
Translations december 2021

### ISSUE THREAD

**Issue by lelikone** [intersystems-community/developer-community#710]
https://docs.google.com/spreadsheets/d/1Wu26cmSiAxgVZon9xZYktQUMl3Xnn0DZXaomw5lZwVo/edit?usp=sharing

**Comment by lelikone** [comment]
Ready. Set. Code.
Want to change how you receive these emails?
You can %updatepref or %unsubscribe.
update your preferences
unsubscribe from this list

**Comment by lelikone** [comment]
Ready. Set. Code.
Want to change how you receive these emails?
You can %updatepref or %unsubscribe.
update your preferences
unsubscribe from this list

**Comment by irinapodmazko** [comment]
Ready
https://docs.google.com/spreadsheets/d/1klrM2w7bE1Sy0XMERrhJ4WlXQG8lYuqs/edit#gid=158039034
