### ISSUE TITLE
ES DC - Not able to open a post for editing

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#717]
Hi!

I was editing a post, saved it and when opened again to finish the edition, I can't open the post anymore. This is the link to the post: [https://es.community.intersystems.com/post/v%C3%ADdeo-el-directorio-de-partners-una-herramienta-fundamental-para-partners-y-usuarios-finales](https://es.community.intersystems.com/post/v%C3%ADdeo-el-directorio-de-partners-una-herramienta-fundamental-para-partners-y-usuarios-finales)

And this is the message that I get:
![imagen](https://user-images.githubusercontent.com/50864675/146354818-f5ebddc9-1fb2-4e8d-a5e1-f0c72ae4bbac.png)

Could you fix it for me?

Thanks!
Esther

**Comment by lelikone** [comment]
@CM-DC-ES 
Hello
Now it is working

**Comment by CM-DC-ES** [comment]
Great! Thanks!! :D
