### ISSUE TITLE
Update badges in accordance with Global Masters

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#718]

**Comment by dyubaylo97** [comment]
@Lena-Ev если мне не изменяет память, задача заключалось в том, чтобы бейджики были все в нормальном качестве подгружены на дс. например:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/25077319/204500190-a3dd3902-5131-4095-9f5b-ade633736481.png">
думаю оч заметна разница

**Comment by lelikone** [comment]
я бы загрузил, но у меня нет этих бейджей.
Те что дают я все обновил

**Comment by dyubaylo97** [comment]
значит надо запросить у Оли

**Comment by lelikone** [comment]
Все что Оля дала, я заменил.

**Comment by dyubaylo97** [comment]
@Lena-Ev с Олей и Алексеем посмотрите пожалуйста - на тебе задачу оставляю

**Comment by Lena-Ev** [comment]
Оля З. еще готовит оставшиеся, тогда оставляем задачу в прогрессе
