### ISSUE TITLE
Broken layout

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#72]
https://community.intersystems.com/post/export-all-code-one-file
![image](https://user-images.githubusercontent.com/1212251/46168689-e0b0b380-c2a1-11e8-9ea0-5df27ca535d5.png)

in answer used markdown
Looks like markdown with one `~~~` without pair can broke layout. In this case it was only once at the end of answer. Currently, I already fixed it.

**Comment by lelikone** [comment]
@daimor 
Hi. Please let me know the original message. Can't reproduce the problem

**Comment by daimor** [comment]
Can't reproduce too. Maybe it's already fixed.
