### ISSUE TITLE
Non-trusted members: how to show their info 

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#720]
All info is shown for admins / moderators. 
For ordinary members – only name and photo + remove block with links: 
<img width="310" alt="image" src="https://user-images.githubusercontent.com/25077319/146534014-88c1b86c-7d8d-4a7d-aa39-b74cfdd57645.png">

**Comment by evshvarov** [comment]
Maybe photo is for trusted too?
