### ISSUE TITLE
Search by members

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#723]
**1.** Search by name and @username at the same time
<img width="237" alt="image" src="https://user-images.githubusercontent.com/25077319/146767045-df5dd57e-3494-459f-96a5-cb45234cfc22.png">

**2.** Search with space - why different results?

- with space - https://community.intersystems.com/members?name=souza+&typesearchuser=users:
<img width="966" alt="image" src="https://user-images.githubusercontent.com/25077319/146766729-da71db69-0600-443a-8f33-fc2d4f900543.png">

- without space - https://community.intersystems.com/members?name=souza&typesearchuser=users:

<img width="971" alt="image" src="https://user-images.githubusercontent.com/25077319/146766778-5580652c-0a83-456e-a925-7b29b62aa2ed.png">

**Comment by Dyubaylo97** [comment]
search by email:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/25077319/149350482-f0944e48-aa56-472a-bee6-fb51d60d7d39.png">

**Comment by dyubaylo97** [comment]
For example, try: 
![image](https://user-images.githubusercontent.com/25077319/149350576-e5993d96-5b70-4369-a0bd-b2c6492f6384.png)
![image](https://user-images.githubusercontent.com/25077319/149350598-e44ea3f2-eb56-4e1a-baff-ac4d613e5c08.png)

**Comment by dyubaylo97** [comment]
enter jonathan sue - Jon Sue Ho should appear
can we do a search by coincidence?

**Comment by dyubaylo97** [comment]
a search by coincidence still not working:
> enter jonathan sue - Jon Sue Ho should appear
<img width="932" alt="image" src="https://user-images.githubusercontent.com/25077319/149815713-96dcec5a-5c84-415f-ab64-75f9c155444b.png">

**Comment by lelikone** [comment]
We don't have that user
