### ISSUE TITLE
ES DC - Can't open a question

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#728]
Hi!

I get an error message when opening this question: [https://es.community.intersystems.com/post/%C2%BFc%C3%B3mo-saber-program%C3%A1ticamente-d%C3%B3nde-se-localiza-un-paquete-mapeado](https://es.community.intersystems.com/post/%C2%BFc%C3%B3mo-saber-program%C3%A1ticamente-d%C3%B3nde-se-localiza-un-paquete-mapeado)

Could you fix it for me?

Thanks!
ES

**Comment by lelikone** [comment]
Hello
fixed
Please don't edit url 
Regards
ALeksey

**Comment by CM-DC-ES** [comment]
ok! Thanks for the tip!
