### ISSUE TITLE
Plus sign in search

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#734]
Search with '+' in text will output just a list of authors, without found content
![image](https://user-images.githubusercontent.com/1212251/147546624-faac6b4b-2e92-4b81-ada9-ef60146488df.png)
https://community.intersystems.com/smartsearch?search=test%2B
Same search without plus sign, shows looks similar results but correctly
![image](https://user-images.githubusercontent.com/1212251/147546814-a40a7836-6d45-492e-a286-a1d2801e5c03.png)
https://community.intersystems.com/smartsearch?search=test

**Comment by lelikone** [comment]
Hello @daimor 
Please check
