### ISSUE TITLE
increase spacing in code samples

### ISSUE THREAD

**Issue by isc-rsingh** [intersystems-community/developer-community#735]
**Is your feature request related to a problem? Please describe.**
Lines of text in <pre> tags is too close together, making it hard to read.
example: the SQL on https://community.intersystems.com/post/integratedml-walkthrough 

**Describe the solution you'd like**
Remove the "line-height: 1" CSS style on <pre> tags so that the line-height is the default, which is a little over 20px.

**Comment by lelikone** [comment]
@isc-rsingh 
Hello!
I changed the styles at your request.
If everything is correct, please close the task.
Regards, Alexey
