### ISSUE TITLE
Fix the related posts 

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#739]
Сценарий:
Связь нужного поста (черновика) была сделана с неверным (опубликованным постом). Зашла в нужный пост (черновик) и изменила связку (previous post) на правильную ссылку - то есть разорвала связь в одном месте. Далее, в нужном посте (в черновике) связь образовалась (появился previous post), но при переходе на previous post (опубликованный пост), связь не образовалась.

**Comment by lelikone** [comment]
@Dyubaylo97 Просим проверить
