### ISSUE TITLE
"Reply" button icon is confusing

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#745]
![image](https://user-images.githubusercontent.com/6726799/151585627-323a6582-3a87-4239-a256-ec591e9c4083.png)

To me this looks like it is going to forward the message. I think the arrow should point the other way in order to convey "reply",

**Comment by gjsjohnmurray** [comment]
It seems to have been changed on the button, but the old icon still appears elsewhere on the page:

![image](https://user-images.githubusercontent.com/6726799/152189669-16922e9c-1b7c-42b8-9b5d-4742ccde8ff1.png)

**Comment by dyubaylo97** [comment]
@gjsjohnmurray fixed! thanks!
