### ISSUE TITLE
LIVE NOW at the Events section

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#749]
https://www.figma.com/file/vfR3fvvJ38Dlz5cz0vLKzD/InterSystems-Community-_New?node-id=5134%3A5520

Note: a new field for link appears on the Create Post page

**Comment by Lena-Ev** [comment]
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/77621970/163792454-3eaff231-3e74-4827-8e8a-388db35f55eb.png">

**Comment by dyubaylo97** [comment]
сможем проверить когда будет Live ивент

**Comment by dyubaylo97** [comment]
не сработало
появился Join now в самом посте, на главной - ничего

**Comment by dyubaylo97** [comment]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/25077319/167442280-308b2946-1af6-4085-a0a3-a16b05c422aa.png">
