### ISSUE TITLE
Store information about moderation activities 

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#766]

**Comment by dyubaylo97** [comment]
в админке
таблица: мембер | активность (модерирующая) | сущность активности | ссылка на коммент/пост/мембера (с превью) | дата самой активности | дата публикации потса/комментария или регистрации пользователя
чтобы можно было фильтровать по каждому параметру

**Comment by Lena-Ev** [comment]
----
1 Вариант - сливаем все в одну таблицу
---
[Date of action] [Moderator name] [Action] [Comment, Post, Member] [Preview][Date of publishing/user registering]
20 June 2022 [Robert Cemper](url) Acceptes answer **Comment** "**[First 50 symbols of comment ....](url)**" 19 June 2022
20 June 2022 [Robert Cemper](url) Declined **Post** "**[Title of the post....](url)**" 19 June 2022
20 June 2022 [Robert Cemper](url) Blocked **Member** "**[Member name Vaysa Ivanov ....](url)**" 19 June 2022



---
Фильтры
---
[Comment, Post, Member] 
[Moderator name]
[Action] 
 - accept answer
 - reject accepted answers

 - approve
 - mark as spam
 - cancel spam

 - post edit - проавливаться в таблицу с историей поста

 - block user
 - make user trusted
 - sent user for moderation

**Comment by lelikone** [comment]
@Dyubaylo97 @Lena-Ev 
Сколько времени хранить эти логи?

**Comment by lelikone** [comment]
![Image](https://user-images.githubusercontent.com/21163767/173003455-20c4ba57-23f2-4a41-aea8-65f36a104686.png)
