### ISSUE TITLE
Search by username: @Name.Name display

### ISSUE THREAD

**Issue by dyubaylo97** [intersystems-community/developer-community#771]
Из такого вида:

![Image](https://user-images.githubusercontent.com/77621970/169783995-593213f4-b742-4b85-9449-263e0c4376db.png)

В такой:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/25077319/158980861-a3bb1412-3a70-469b-8539-92d102ae029b.png">

https://www.figma.com/file/vfR3fvvJ38Dlz5cz0vLKzD/InterSystems-Community-_New?node-id=6259%3A15524

**Comment by Lena-Ev** [comment]
надо добавить дизайн, чтобы можно было удалять выбранных пользователей

**Comment by Lena-Ev** [comment]
так как тут только по одному можно искать, то оставить такой вариант, можно по крестику его удалить


![Image](https://user-images.githubusercontent.com/77621970/173303070-c05568f8-d062-413b-85d3-2627a2414b98.png)
