### ISSUE TITLE
Unable to publish a new post after initially previewing it

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#773]
Here's what I think I did:

1. Wrote a new article
2. Clicked "Preview"
3. Used the link to go back and edit it.
4. Added a teaser split marker.
5. (maybe clicked "Save")
6. Clicked "Publish".

A header banner told me that the article already existed.

In the end I removed a word from the title and was able to publish it.

Browser is FF 98.0.2

**Comment by dyubaylo97** [comment]
Hi John, 
There can't be articles with the same title on the DC  website - maybe that's why you couldn't save your post. 
What was the original title of your article?

**Comment by gjsjohnmurray** [comment]
> What was the original title of your article?

The one I ended up being able to publish is https://community.intersystems.com/post/docker-containers-windows-sometimes-unable-get-ports-during-startup

I no longer remember the original title. Perhaps it was:

"Docker Containers on Windows sometimes unable to get **its** ports during startup"

(extra **its**)

**Comment by dyubaylo97** [comment]
Hmm, strange thing 
We tried to reproduce your scenario, but it didn't work

**Comment by gjsjohnmurray** [comment]
OK, closing it.
