### ISSUE TITLE
Анонс на конкурс

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/developer-community#777]
Ещё надо сделать так, чтобы главный конкурсный анонс добавлялся в блок Events на главную 
У нас была задачка для логики тегов в конкурсных анонсах 
Дополнить надо, то есть про тегах Iris contest + events + заполняем даты = главный анонс попадает на главную в блок справа 
(Никаких доп кнопок /блоков в самом анонсе не появляется)

**Comment by lelikone** [comment]
Давайте уточним.
1. Вернуть показ в ивентах с тегом айрис контестк
2. НЕ показывать блок справа в самом посте?
