### ISSUE TITLE
Поп ап на подписки при первом входе на ДС

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/developer-community#778]
Надо попап делать при первом входе, с двумя чекбоксами включенными подписки на дайджесты и посты. @adyubaylo @now_and_happy  - сделайте плиз? А то мы партизански подписываем людей и они нас потом могут меньше любить за это 😉

**Comment by Lena-Ev** [comment]
@InnaGenova 

Заголовлок попапа:
Subscribe me to:
В попапе указать 2 опции(пока так, может потом поменяем какие и текст):
<img width="404" alt="image" src="https://user-images.githubusercontent.com/77621970/164230812-2ac12302-7882-4e81-99f7-7b19d493925c.png">
<img width="438" alt="image" src="https://user-images.githubusercontent.com/77621970/164230968-1cbac8ea-60aa-419e-b288-1ffbf5d067fa.png">

Под этими кнопками - текст
View other subscriptions and notifications settings here

Одна кнопка 
Submit

**Comment by InnaGenova** [comment]
@Lena-Ev  
где поп ап должен появляться?
1. по середине экрана с затемненным бэкграундом
2. всплывать в правом нижнем углу

**Comment by Lena-Ev** [comment]
Вот такого типа:
https://www.figma.com/file/vfR3fvvJ38Dlz5cz0vLKzD/InterSystems-Community-_New?node-id=3216%3A0
<img width="557" alt="image" src="https://user-images.githubusercontent.com/77621970/165291545-665153c0-4dfa-4bce-b1cf-f9b000fcf565.png">

**Comment by InnaGenova** [comment]
@Lena-Ev 
https://www.figma.com/file/CLB6H6IfawgvugGRv6XE0k/InterSystems-Community-_New-(Copy)?node-id=786%3A0

**Comment by Lena-Ev** [comment]
@Dyubaylo97 проверь пожлста https://www.figma.com/file/CLB6H6IfawgvugGRv6XE0k/InterSystems-Community-_New-(Copy)?node-id=7433%3A19460
<img width="647" alt="image" src="https://user-images.githubusercontent.com/77621970/166413593-09a157f3-66c6-4db5-8853-0fc6354b57a6.png">

**Comment by dyubaylo97** [comment]
- Weekly Community digest 
Receive weekly digest of articles, questions, announcements, etc.
- Monthly Community digest
Receive monthly digest of articles, questions, announcements, etc.
- Auto-subscribe for my commented posts
Automatically subscribe to posts where I left a comment.

добавить по сути только Monthly Community digest + точки в конце

сделать посередине надпись:
[Set up your other Community subscriptions here.](гиперссылка на весь текст)

**Comment by InnaGenova** [comment]
@Dyubaylo97
@Lena-Ev  
готово
https://www.figma.com/file/CLB6H6IfawgvugGRv6XE0k/InterSystems-Community-_New-(Copy)?node-id=7433%3A19460

**Comment by dyubaylo97** [comment]
Точку в конце последней фразы и супер! Спасибо :)

**Comment by InnaGenova** [comment]
есть, готово))

**Comment by Lena-Ev** [comment]
@lelikone 
при первом логине показывать такой диалог и соответсвенно подписывать людей на рассылки
По ссылке перед кнопкой - человек переходит в настройки его подписок
https://community.intersystems.com/user/289081/subscriptions

<img width="353" alt="image" src="https://user-images.githubusercontent.com/77621970/167422093-40795b09-d3d6-4db7-b652-e9deac5a331c.png">

**Comment by Lena-Ev** [comment]
@Dyubaylo97 надо подумать еще над приветсвенным словом может? не сразу рассылкой пулять?

**Comment by dyubaylo97** [comment]
самое простое: Hello and Welcome to InterSystems Developer Community!
ну и кажется что в поп-ап не надо впихивать какой-то абзац текста - что думаешь?

**Comment by Lena-Ev** [comment]
@InnaGenova добавь плиз еще в попап текст 
Welcome to InterSystems Developer Community! Please customize your subscriptions & email notifications and complete your profile:

Вместо заголовка subscribe me to

**Comment by InnaGenova** [comment]
@Lena-Ev 
готово
https://www.figma.com/file/CLB6H6IfawgvugGRv6XE0k/InterSystems-Community-_New-(Copy)?node-id=7433%3A19460

**Comment by Lena-Ev** [comment]
@lelikone согласовали поп-ап по ссылке из комментария выше (добавили тот текст)

При первом входе человека оставляем на главной (не делаем редирект на настройки как сейчас)
и показываем ему этот попап
<img width="874" alt="image" src="https://user-images.githubusercontent.com/77621970/167842426-079ffd2e-05b2-4406-b2bc-1c1048a94c0a.png">

**Comment by Lena-Ev** [comment]
почему то показывает попап и мне и Насте
и поменять цвет текста - на черный как в фигме
