### ISSUE TITLE
Пофиксить мобилку (трелло)

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/developer-community#780]
https://trello.com/c/UdtXOw1R/489-%D0%BF%D0%BE%D1%84%D0%B8%D0%BA%D1%81%D0%B8%D1%82%D1%8C-%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D0%BA%D1%83
кнопки склеились
сама страница не зафиксирована

![image](https://user-images.githubusercontent.com/77621970/162740352-35361b90-019e-4cc8-9a3e-c1adcfb5a9ad.png)

**Comment by dyubaylo97** [comment]
![image](https://user-images.githubusercontent.com/25077319/163805392-5844f8d0-e922-40a5-9f9f-141b5d2d2477.png)

Страница не ездит. Но кнопка склеена.

**Comment by Lena-Ev** [comment]
@lelikone увеличить расстояние между кнопками(кнопкой) и текстовым блоком (10px)

**Comment by dyubaylo97** [comment]
в соответсивии с макетом - 10px

**Comment by lelikone** [comment]
Подправил

**Comment by dyubaylo97** [comment]
![IMG_9944](https://user-images.githubusercontent.com/25077319/164225965-e09eaac1-e19a-4fc4-8731-68a3c9e242e0.PNG)
 все также
