### ISSUE TITLE
Проверить табличку с рассылками, что то еще добавить?

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/developer-community#781]
<img width="486" alt="image" src="https://user-images.githubusercontent.com/77621970/163554936-4bc81c1c-006e-424d-a365-1492ac378a6b.png">

**Comment by dyubaylo97** [comment]
https://docs.google.com/spreadsheets/d/1hjY-CR-ulye8Y05ORT4jBBl_cFA92sbsdhHRE1e8fqU/edit#gid=1267223398

**Comment by dyubaylo97** [comment]
<img width="446" alt="image" src="https://user-images.githubusercontent.com/25077319/167440552-f775abba-b9da-4901-b86f-903087013a2d.png">

**Comment by dyubaylo97** [comment]
вижу что просила, добавили 
просьба отписываться, если это уже сделано
