### ISSUE TITLE
In French version Events tag doesn't work as it should

### ISSUE THREAD

**Issue by Gra-ach** [intersystems-community/developer-community#792]
In French version, tag 'Events' spell 'événements'. And when the announcement is added it works fine and shows the new fields about this event, like the place, dates etc. But if it is already created and someone wants to edit it, after the edit, all the fields concerning the event vanish and the event is no longer in the block 'Evenements' on the main page. 
![image](https://user-images.githubusercontent.com/9782856/167264855-91530a19-4187-451e-8faf-fc4117c11eff.png)
And someone has to edit it once more, delete the tag, add it again and fill in the necessary data again.
![image](https://user-images.githubusercontent.com/9782856/167265110-a4f5937f-1daa-4660-a26b-b384214eb09a.png)

**Comment by Lena-Ev** [comment]
@Gra-ach could you please test this

**Comment by Gra-ach** [comment]
Работает. Спасибо!
