### ISSUE TITLE
Wrong order of author and article name in Subscriptions Digest in French DC

### ISSUE THREAD

**Issue by Gra-ach** [intersystems-community/developer-community#794]
In the Subscriptions Digest, the name of the author and the name of the article are switched:
![image](https://user-images.githubusercontent.com/9782856/167265417-1a35b8f9-9343-4d76-890e-31a7ce8e8aca.png)
So basically it says: 'Article name' has added a new article 'Author name' not vice versa.

**Comment by Lena-Ev** [comment]
switch author name and article name

**Comment by Gra-ach** [comment]
Works fine now
