### ISSUE TITLE
ES DC - Translation for scheduled posts

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#798]
Hi!

Could you please translate these two sentences used when publishing a post?
* Instead of "Publish now" it is "Publicar ahora"
* Instead of "Schedule post" it is "Programar publicación". If this sentence in Spanish is too long, you could just put "Programar"

Thank you.
![imagen](https://user-images.githubusercontent.com/50864675/172574524-17ace6d9-f7de-415c-8fa5-ee39d5b5bb74.png)

This button should also be translated: "Programar publicación" (or just "Programar")
![imagen](https://user-images.githubusercontent.com/50864675/172576197-219feddb-ac47-4c0d-a458-316dae1420af.png)

**Comment by lelikone** [comment]
Please check

**Comment by CM-DC-ES** [comment]
Great, thanks!
