### ISSUE TITLE
Allow to set default mode of comments/posts to markdown

### ISSUE THREAD

**Issue by kazamatzuri** [intersystems-community/developer-community#8]
It should be made possible to change my personal default to use 'plain text (markdown)' for comments/posts/answers

**Comment by evshvarov** [comment]
Internal task: DCE-354

**Comment by lelikone** [comment]
I propose to make more comfortable. The user selects an input type and remembers that type after the message is sent. If you need to change, it changes, sends a comment and the site remembers the last type of input.
