### ISSUE TITLE
French community (log in)

### ISSUE THREAD

**Issue by irinapodmazko** [intersystems-community/developer-community#800]
When [Adeline](https://fr.community.intersystems.com/user/adeline-icard) from the Fr Community log in to the system, she appeared at first on the En community, and then she have to switch each time to the Fr community
Could you please check the reason? What steps does she have to take?

**Comment by lelikone** [comment]
We solved this error in another problem, double-check it now.

**Comment by Lena-Ev** [comment]
@irinapodmazko could you check if it works now?
Reopen the issue if it doesn't work, please
