### ISSUE TITLE
Search within my own posts and replies

### ISSUE THREAD

**Issue by mcmundt** [intersystems-community/developer-community#802]
Sometimes a user will post a question that I know I've answered before for someone else and I want to point them to my previous reply. 

Maybe this already exists, but I don't see a good way to search through my own posts and replies. It would be great if we could add a search box to the "posts" page under a user's account to search within all posts and replies by that user.

The search page has a "Search by user posts" box which accepts a user name, but this seems to only search posts created by the specified user. In my use case the posts were created by someone else and I want to search in my replies.

**Comment by eduard93** [comment]
Workaround: google search for:

```
site:community.intersystems.com eduard <query>
```

it works decent enough.

**Comment by Lena-Ev** [comment]
The task is passed to UX designer #144

**Comment by Lena-Ev** [comment]
@eduard93 @mcmundt  your request is implemented
and even more)
Now you can search through:
you posts
your replies
Your drafts
your direct messages
