### ISSUE TITLE
Some menu items are missing in Japanese site

### ISSUE THREAD

**Issue by miniclub** [intersystems-community/developer-community#807]
Hello everyone,
The below items in 'Event' menu are missing from Japanese site.

  Tech Article Contest
  Event Calendar

Could you please add the items?
Regards,

Toshihiko Minamoto

**Comment by dyubaylo97** [comment]
Thanks for noticing, Toshihiko! We'll add these items shortly.

@lelikone ^

**Comment by Lena-Ev** [comment]
@miniclub We have added the options to the menu but do you want to translate them in Japanese, or keep them in english as they lead to english pages?

**Comment by miniclub** [comment]
Sorry for the delay.

I would like to translate the menu in Japanese.
Could you please make the following changes?

  InterSystems Idea-A-Thon    =>  InterSystems アイデアソン
  Tech Article Contest     =>   技術文書コンテスト
  Programming Contest  =>  プログラミングコンテスト  

Regards,

Toshihiko Minamoto

**Comment by lelikone** [comment]
@miniclub 
Hello Toshihiko.
Translation of the links in the menu is done.

**Comment by miniclub** [comment]
Thank you all.
I have confirmed that it has been updated.
