### ISSUE TITLE
关于安装odbc在ubuntu 1804 但是无法正常连接iris

### ISSUE THREAD

**Issue by 1009058470** [intersystems-community/developer-community#808]
我参阅得文档
[https://docs.intersystems.com/iris20222/csp/docbook/DocBook.UI.Page.cls?...](https://docs.intersystems.com/iris20222/csp/docbook/DocBook.UI.Page.cls?KEY=BNETODBC)

我使用得方式
[https://docs.intersystems.com/iris20222/csp/docbook/DocBook.UI.Page.cls?...](https://docs.intersystems.com/iris20222/csp/docbook/DocBook.UI.Page.cls?KEY=BNETODBC_unixodbc#BNETODBC_unixodbc_odbcinst)

我使用得是unixodbc版本
unixODBC 2.3.4

系统版本(ubuntu 1804)
```
uname -a
Linux DESKTOP-TFPBPQU 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
```
我使用得驱动如下
ODBC-2020.1.2.517.0-lnxubuntux64.tar.gz 不生效

ODBC-2022.1.0.209.0-lnxubuntu1804x64.tar.gz 不生效

我得问题
数据库所在电脑和odbc所在电脑都没有防火墙 ,无法通过isql通过定义得dsn连上数据库， 也无法通过程序连接到数据库

得到得错误
```
DSN=iris;UID=_system;pwd=sys
ERROR [08S01] [unixODBC][Iris ODBC][State : 08S01][Native Code 461]
[libirisodbcu35.so]
Communication link failure
```

isql iris
[ISQL]ERROR: Could not SQLConnect
产品版本: IRIS 2020.1

**Comment by Lena-Ev** [comment]
@1009058470 I suppose you wrote to the wrong place, here are we get and process issues for the website https://community.intersystems.com/

If you need help with your question you can post it there in Chinese website https://cn.community.intersystems.com/
