### ISSUE TITLE
A error using net5 System.Data.Odbc to connet iris db 

### ISSUE THREAD

**Issue by 1009058470** [intersystems-community/developer-community#809]
### platform 
ubuntu using unixOdbc dirver 

#### Describe the problem you're observing:
using dotnet nuget System.Data.Odbc  to connet the iris for some sql will have bug on linux,but it is ok on windows 
and that driver is ok for other db type .
I have put a issue on dotnet also (https://github.com/dotnet/runtime/issues/80015)
Is anyone can have a look for that

**Comment by Lena-Ev** [comment]
Hello! Here we accept only issues connected to the https://community.intersystems.com/ website.

To get an answer to your question you may create a post here https://community.intersystems.com/ and our members or Intersystems employees will get in touch with you.

**Comment by 1009058470** [comment]
> Hello! Here we accept only issues connected to the https://community.intersystems.com/ website.
> 
> To get an answer to your question you may create a post here https://community.intersystems.com/ and our members or Intersystems employees will get in touch with you.

emmm the docs websit says that i can ask the question here, to post a issus here

**Comment by 1009058470** [comment]
> Hello! Here we accept only issues connected to the https://community.intersystems.com/ website.
> 
> To get an answer to your question you may create a post here https://community.intersystems.com/ and our members or Intersystems employees will get in touch with you.

And there also send a mail to me when i post on [that](https://community.intersystems.com/) website.

Thank you for submitting a new post to [InterSystems Developer Community](https://community.intersystems.com/)! Our moderators will review it as soon as possible. You will be notified when your post is published.

Your post: "[A issus when using dotnet System.Data.Odbc nuget to connet the iris](https://community.intersystems.com/node/533311)"

If you have not received any feedback within 24 hours, please submit an issue on [InterSystems Developer Community GitHub](https://github.com/intersystems-community/developer-community).
