### ISSUE TITLE
"Accepted answer" notification text implies there is only one accepted answer

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#811]
![image](https://user-images.githubusercontent.com/6726799/212294701-28d53c6f-a506-4308-8f0c-bdbde464e71b.png)

I suggest "the" gets changed to "a" because it is now possible for more than one reply to be accepted.

**Comment by dyubaylo97** [comment]
thanks for noticing this, John! we'll fix it asap :)

**Comment by Lena-Ev** [comment]
@lelikone could you please change "the" to "a" in this text on English community

**Comment by lelikone** [comment]
Please check

**Comment by gjsjohnmurray** [comment]
Confirmed fixed. Thanks!

![image](https://user-images.githubusercontent.com/6726799/212734527-5b951210-7624-4a80-9005-c1c67756ff9e.png)
