### ISSUE TITLE
Translation management (unknown requested articles)

### ISSUE THREAD

**Issue by irinapodmazko** [intersystems-community/developer-community#812]
In translation management, from time to time, such articles appear in the featured posts with an unknown person who chose the translation.
An unauthorized user cannot select.
And if authorized, it is always displayed in the Approvals column

the situation is usually the same for other languages
Please help me with this bug.

**Comment by lelikone** [comment]
All of these posts are automatically translated because there are rules for them in the form of matching certain tags
