### ISSUE TITLE
[minor] No "New Post" button when in search mode

### ISSUE THREAD

**Issue by bdeboe** [intersystems-community/developer-community#815]
**Is your feature request related to a problem? Please describe.**
Usually, the top DC bar (right below the navigation) has both a search field and a "New Post" button. When viewing search results, the search field disappears from this bar (becoming a more expressive form in the main content area), but the "New Post" button is also gone. Clicking on the "All Posts", "Questions" and other post-type links on the left just filters the search results (which is good), but I think it'd be useful to have the one-click option to start a new post at all times.

**Describe the solution you'd like**
Consider simply not hiding the "New Post" button when in search mode. There's no real reason to hide it or treat it differently vs any other browse context

**Comment by Lena-Ev** [comment]
Thank you !
We will check on that, should be possible

**Comment by lelikone** [comment]
I did it.

**Comment by dyubaylo97** [comment]
Hi @bdeboe! We implemented it - thanks for sharing!
If you have any other suggestions, please feel free to share with us.
