### ISSUE TITLE
CRLF lost from code block content during translation

### ISSUE THREAD

**Issue by imess33** [intersystems-community/developer-community#816]
#### Describe the problem you're observing:

when I translated a post from english to chinese, CRLF was lost for code block, such as javascript and python code block. Multiple lines in the code block display as one line in translated copy. 

#### Steps to reproduce, if exist:

here is the post I translated : https://community.intersystems.com/post/chatgpt-create-message-transformations-you

**Comment by Lena-Ev** [comment]
hello!
Looks like it is the same on both posts
may be that was a temporary bug, please reopen issue is that repeats
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/77621970/219606142-f51ba533-afa6-40a4-92dc-b776e15b7e47.png">

<img width="919" alt="image" src="https://user-images.githubusercontent.com/77621970/219605953-849b4b46-35da-4778-9f59-1b5cf4954a50.png">
