### ISSUE TITLE
Error trying to access Cache using IRIS ADO.NET "InterSystems IRIS Provider is not compatible with Cache xDBC server"

### ISSUE THREAD

**Issue by markd11** [intersystems-community/developer-community#817]
I am upgrading an application from dotNet Framework to dotNet Core.
Prior to the upgrade I was able to connect to both my Cache & IRIS instances using the IRIS ADO.NET driver.
However, in dotNet Core, whilst I can connect to IRIS, I get the following error connecting to Cache.
InterSystems IRIS Provider is not compatible with Cache xDBC server
 
I am using the IRIS  driver from the Windows (x86-64) 2022.1 distribution (the one in dev\dotnet\bin\net5.0).
The cache version is Cache for Windows (x86-64) 2018.1.2

https://community.intersystems.com/post/i-get-following-error-trying-access-cache-using-iris-adonet-intersystems-iris-provider-not

**Comment by dyubaylo97** [comment]
Hello!
DC GitHub is a place to introduce issues and feature requests for [Developer Community site](https://community.intersystems.com/). All questions related to InterSystems technology can be asked on Community, as you've already done. Thanks!
