### ISSUE TITLE
Languages available to translate a post

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#828]
When you click on the language button, you see the Chinese and Japanese language written in Chinese and Japanese:

![imagen](https://user-images.githubusercontent.com/50864675/223099899-90be9f18-1810-4648-a45a-fb403d20a263.png)

But when you click on any of the languages, on the next page you see the Chinese and Japanese options written in English:

![imagen](https://user-images.githubusercontent.com/50864675/223100326-cce078b4-6654-4689-ac35-1026ae610565.png)

So just wondering if the texts on the last image shouldn't appear in Chinese and Japanese?

Thanks!
Esther

**Comment by Lena-Ev** [comment]
We will translate these tab-names too.
That was a request that we are implementing.

**Comment by CM-DC-ES** [comment]
ok, thanks! I close the issue then.
