### ISSUE TITLE
ES DC - Name of a tag

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#829]
Hi! Could you please change the name of a tag in the Spanish DC?

Instead of "Inicio" it should be "Startup", as in English.

Thanks!

**Comment by lelikone** [comment]
ok

**Comment by CM-DC-ES** [comment]
Thanks! This tag sounds also weird in Spanish: #La comunidad de desarrolladores oficial

Could you change it and put "Comunidad de Desarrolladores Oficial"?

**Comment by lelikone** [comment]
ok

**Comment by CM-DC-ES** [comment]
Thanks!
