### ISSUE TITLE
Add  #Archived TAG for posting

### ISSUE THREAD

**Issue by rcemper** [intersystems-community/developer-community#833]
**Is your feature request related to a problem? Please describe.**
I suggest having a TAG #Archive to signal outdated Posts (DC) or packages (DC)

**Describe the solution you'd like**
Posts with this tag should be excluded from Searching and be locked for replies.
Setting the flag should block Update Date.

**Describe alternatives you've considered**
as an alternative, I added *** archived **on top of my old posting
But that pushed them as FRESH updated on the News list.

**Additional context**
At least for moderators Re-Setting the publishing date (by SQL) should be an option

I met the problem with announcements and Invitations to Events 5 years back.
Totaly our of date.  Same for problems  of caché 2015 ...fixed since long a out-of-date

**Comment by dyubaylo97** [comment]
Hi Robert, 
Already in implementation. We will notify you when this is done. Thank you!

**Comment by rcemper** [comment]
GREAT !, I like it
