### ISSUE TITLE
Spelling error - "previosly"

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#843]
When composing a new post:

![image](https://github.com/intersystems-community/developer-community/assets/6726799/cbe161bc-ae07-4db7-98d5-f49663d3fb2a)

**Comment by dyubaylo97** [comment]
Hi John, 
Thanks for noticing this! We'll fix it asap.

**Comment by Lena-Ev** [comment]
@lelikone  introduce the hot fix on the prod please - "previously"

**Comment by lelikone** [comment]
The error has been corrected

**Comment by gjsjohnmurray** [comment]
Thanks!
