### ISSUE TITLE
change the logic of a word in the translation portal

### ISSUE THREAD

**Issue by irinapodmazko** [intersystems-community/developer-community#844]
Please change the status "translated" to "published" in the Selected posts

So it should be:
New
On translate
Draft
Published

![telegram-cloud-photo-size-2-5379965254781488819-y](https://github.com/intersystems-community/developer-community/assets/44035497/299f145d-296c-4902-aff3-0de81e827523)

**Comment by lelikone** [comment]
@irinapodmazko The drop-down list has been updated
