### ISSUE TITLE
Make it easy to find where to report an issue from the D.C. interface

### ISSUE THREAD

**Issue by isc-bspead** [intersystems-community/developer-community#846]
Provide a "Report an Issue" button / link somewhere easy to find in the D.C. UI (without sign-in required) which points to:

https://github.com/intersystems-community/developer-community/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

This will make it easier for people to report when something is broken and probably will prevent calls to Support.

**Comment by Lena-Ev** [comment]
@isc-bspead Ben thank you for  your idea, now this link is in the About menu and is available to any visitor of the community.
If you have any ideas where you would better see this link just let us know.
<img width="1230" alt="image" src="https://github.com/intersystems-community/developer-community/assets/77621970/e61553eb-0bed-4c5c-8481-7241c09c452f">

Just note if we put the button on the main page it may be confused with posting an issue about InterSystems software not community website (we had such a case)

**Comment by isc-bspead** [comment]
Thank you!  I hadn't found that option but that does what I need.  I agree it doesn't make sense to put it at the top level - this is just a training issue (and now I have been trained).
Thanks!!
