### ISSUE TITLE
ES DC - email footer

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#847]
hi! Could you please change some of the translations on the email footer in Spanish?

![imagen](https://github.com/intersystems-community/developer-community/assets/50864675/97d55547-280d-4fc9-8400-17f71dec8f9c)

They should be:

* Community - Comunidad (it is ok now)
* Open Exchange - Open Exchange (non-translatable)
* Global Masters - Global Masters (non-translatable)
* Learning - Formación
* Documentation - Documentación (it is ok now)
* Ideas portal - Portal de Ideas
* Developer Hub - Developer Hub (non-translatable)
* Ready. Set. Code - Ready. Set. Code (non-translatable)

Thank you!
Esther

**Comment by Lena-Ev** [comment]
@lelikone Could you look into this task if you have spare time this week, otherwise we will move it to the next one

**Comment by lelikone** [comment]
@CM-DC-ES @Lena-Ev @Loquinha 
Hello Esther!
The phrases have been changed, the corrected phrases will be sent in future digest mailings

**Comment by CM-DC-ES** [comment]
Great, thank you!
