### ISSUE TITLE
Can not connect to intersystems-community

### ISSUE THREAD

**Issue by ebaugues** [intersystems-community/developer-community#848]

**Comment by Lena-Ev** [comment]
@ebaugues could you provide your email which you use for login? we will check it.

**Comment by ebaugues** [comment]
***@***.***
    	Get Outlook for iOS
    
  

 From: Lena-Ev ***@***.***>Sent: Thursday, September 28, 2023 11:44 AMTo: intersystems-community/developer-community ***@***.***>Cc: ebaugues ***@***.***>; Mention ***@***.***>Subject: Re: [intersystems-community/developer-community] Can not connect to intersystems-community (Issue #848) 
@ebaugues could you provide your email which you use for login? we will check it.

**Comment by Lena-Ev** [comment]
@ebaugues I assume GitHub removes emails from the messages, could you please send just the letters before @ 
<img width="386" alt="image" src="https://github.com/intersystems-community/developer-community/assets/77621970/effe4801-807d-4f3a-bd4a-d04dc3178c5a">
