### ISSUE TITLE
Suggestion for the "Subscriptions" page

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#851]
Hi! In the "Subscriptions" page, the first thing that you see is the "Digest mode for email subscriptions", where you can choose that mode or not. But in my opinion that option should be shown after you have chosen which notifications you want to receive. And then you choose the digest mode or not. The way is now is a bit confusing, since you are asked to choose a digest mode before you have chosen anything. My suggestion:

![Captura de pantalla 2023-12-11 a las 12 33 12](https://github.com/intersystems-community/developer-community/assets/50864675/8d6a006e-66f5-4b87-82db-748e8521070b)

Thanks!
Esther

**Comment by Lena-Ev** [comment]
@dyubaylo97 could you comment please?

**Comment by dyubaylo97** [comment]
Hi Esther! Thanks for your feedback. 
We'll announce the redesigned subscription page in the next DC release - let's see what feedback we'll get from our users.

**Comment by CM-DC-ES** [comment]
ok! Thank you!
