### ISSUE TITLE
ES DC - Translation in the post with the 2023 recap

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#852]
Hi! The image created by default to share the 2023 recap has some words mistranslated:

* "Mi recapitulación del 2023 en la Comunidad de desarrolladores de InterSystems" should be "Mi resumen de 2023 en la Comunidad de Desarrolladores de InterSystems"
* "Debates" should be in singular, as it is just 1. So "Debate"
* "Echa un vistazo a mi resumen del año 2023 para la Comunidad de desarrolladores de InterSystems" should be "Echa un vistazo a mi resumen del año 2023 en la Comunidad de Desarrolladores de InterSystems"

![imagen](https://github.com/intersystems-community/developer-community/assets/50864675/c096ca53-471a-48e5-87b5-d1e7de4818d9)

**Comment by CM-DC-ES** [comment]
Hi! Could I know why have you closed the issue? The image with the errors hasn't been changed.

Thank you.
ES

**Comment by Lena-Ev** [comment]
by mistake, will be changed

**Comment by voleynik2** [comment]
@Lena-Ev @dyubaylo97 

1.I change phrase "Echa un vistazo a mi resumen del año 2023 para la Comunidad de desarrolladores de InterSystems" translation - it's the simplest.
2.To change the phrase in the generated picture, the designers need to change the text in the figma in all Spanish layouts and I will take new pictures
3.Words in button layouts are always plural, designers need to make two sets of buttons for singular and plural for all languages, I will export to pictures and add a condition to the code to use a picture with singular or plural depending on the number.

![image](https://github.com/intersystems-community/developer-community/assets/131883746/cd20f97e-cad5-4035-b329-19c2e3a4d5f1)

**Comment by Lena-Ev** [comment]
@voleynik2 
2- changed
3 - keep in multiple for now, as it is a summary not a sentence

**Comment by voleynik2** [comment]
@Lena-Ev complete on test server, wait for Alexey to transfer to prod

**Comment by lelikone** [comment]
Выложено на проде, но рекап уже отключен

**Comment by Lena-Ev** [comment]
@CM-DC-ES we have updated the translation and will keep it till the next recap

**Comment by CM-DC-ES** [comment]
Cool, thanks!
