### ISSUE TITLE
In the email subject, add a colon after the type of post 

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#853]
Hi! Could you add a colon, or a hyphen or a vertical bar, after the type of post in the email subject? For example:

Instead of "Nuevo artículo Datos desde IRIS a Google Big Query - InterSystems Cloud SQL mediante Dataflow"
![imagen](https://github.com/intersystems-community/developer-community/assets/50864675/ec7e39e5-cd97-4816-a21c-3e4bdcdd8a9d)

you could put: 
"[DC ES] Nuevo artículo: Datos desde IRIS a Google Big Query - InterSystems Cloud SQL mediante Dataflow" 
or: 
"[DC ES] Nuevo artículo | Datos desde IRIS a Google Big Query - InterSystems Cloud SQL mediante Dataflow" 

Thanks!
ES

**Comment by lelikone** [comment]
@CM-DC-ES 
For the subject line, I added the symbol : I have already received several emails with the modified header

![Image](https://github.com/intersystems-community/developer-community/assets/21163767/123d8646-29d4-4819-a55c-6511b63a3fae)

**Comment by CM-DC-ES** [comment]
Thank you Aleksey!

The only problem with the colon is when it is used by the author in the title of the article, like in this case:
"What to do with the error 5369: Class is currently being compiled by process"

Then, the subject line will show like this:
New article: What to do with the error 5369: Class is currently being compiled by process

That is, two colons in the same line.

So, what do you think about this? Do we keep the colon? The only symbol that is not used in the titles is the vertical bar, since the dash is also used.

ES

**Comment by lelikone** [comment]
@dyubaylo97 ^

**Comment by dyubaylo97** [comment]
It seems like it's not that common to see articles with a colon in the title bar. Let's keep the update that Alexey has already implemented. Thank you both!! :)

**Comment by CM-DC-ES** [comment]
Cool, thanks!!
