### ISSUE TITLE
ES DC - Articles not ordered correctly by number of visualizations

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#854]
Hi!
I've just published the announcement with the recap of the best articles in 2023 in the ES DC and I've realized that in the section called "Most popular articles" ("Artículos más leídos" in Spanish), the articles are not ordered by number of visualizations, which is a bit weird. So just wondering if you could fix it for me?
This is [my post](https://es.community.intersystems.com/post/los-mejores-art%C3%ADculos-de-la-comunidad-de-desarrolladores-durante-2023) 
This is the part that I'm referring to:
![Captura de pantalla 2024-01-09 a las 11 25 24](https://github.com/intersystems-community/developer-community/assets/50864675/053d9a9b-c2d2-43ad-84e3-64b066cc9f5b)

Thanks
ES

**Comment by Lena-Ev** [comment]
@dyubaylo97 could you comment please.
This was done utilising the formula, not just views

**Comment by dyubaylo97** [comment]
No, there's a miscalculation here. We'll fix it.
Thanks for noticing this, @CM-DC-ES!!

**Comment by lelikone** [comment]
@Lena-Ev @dyubaylo97 
The calculation formula has been changed. All announcements have been changed manually on all sites.

**Comment by lelikone** [comment]
@Loquinha You can run a check

**Comment by dyubaylo97** [comment]
It seems like it's not that common to see articles with a colon in the title bar. Let's keep the update that Alexey has already implemented. Thank you both!! :)

**Comment by dyubaylo97** [comment]
thank you!!

**Comment by Loquinha** [comment]
Now are listed as descending according to the number of views:
![image](https://github.com/intersystems-community/developer-community/assets/113416329/bfea7856-f438-4e05-928f-902842cbca93)
![image](https://github.com/intersystems-community/developer-community/assets/113416329/949164ae-abb9-442c-a0c8-64e5dfb117d2)
![image](https://github.com/intersystems-community/developer-community/assets/113416329/667427cb-290f-43fc-bd2a-9baf1d30e5d0)








@lelikone Is it different for PT community? [this post ](https://pt.community.intersystems.com/post/principais-artigos-de-2023-para-desenvolvedores-intersystems)
![image](https://github.com/intersystems-community/developer-community/assets/113416329/0aedddd6-f006-4593-bc98-a6bb212b3572)

**Comment by lelikone** [comment]
In Portuguese, it's not generated content - they're the ones who made their own translation of the English digest, which they shouldn't have done. If it needs to be changed, they can do it themselves.

**Comment by lelikone** [comment]
@Loquinha

**Comment by Loquinha** [comment]
ok, thank you all

**Comment by Lena-Ev** [comment]
@CM-DC-ES If everything worked out for you could you please close the issue

**Comment by CM-DC-ES** [comment]
Sorry, forgot to close the issue. Thank you for your work!
