### ISSUE TITLE
Number of items on the "Official certification" section

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#856]
Hi!
Not important, but on the main page of the profiles, the 'certifications' section of the menu doesn't show the number of items, while the rest of the sections does show it. So just wondering if the number could be added?
![imagen](https://github.com/intersystems-community/developer-community/assets/50864675/f342569b-ade6-449f-a32b-a9a49112d061)
Thanks!
Esther

**Comment by dyubaylo97** [comment]
Esther, thanks for the idea! @Lena-Ev, please take this issue into the dev plan

**Comment by voleynik2** [comment]
@Lena-Ev @Loquinha complete (at prod server)

![Image](https://github.com/intersystems-community/developer-community/assets/131883746/504ea414-0046-47ef-9f4f-2734b7cbe635)

**Comment by CM-DC-ES** [comment]
Cool! Thank you!!
