### ISSUE TITLE
Пауза для гифок в комментариях

### ISSUE THREAD

**Issue by Lena-Ev** [intersystems-community/developer-community#857]

**Comment by voleynik2** [comment]
@Lena-Ev @Loquinha готово на тестовом

**Comment by Loquinha** [comment]
спасибо
@voleynik2 посмотри, плиз
 - поставила в реплай только гиф без слов - выдал вот что , не знаю насколько критично это на тестовом, на второй реплай ок все, без проблем, может из за кеша?
![image](https://github.com/intersystems-community/developer-community/assets/113416329/bfa9a4cc-c88b-4b27-ae5a-72c3bc80ae48)



 - потом добавила пару слов и сохранил, все работает
![image](https://github.com/intersystems-community/developer-community/assets/113416329/006ef6eb-b59c-46ad-b4a9-b3ff09b68ba9)

**Comment by voleynik2** [comment]
@Loquinha 1.Если только картинка в комменте, без букв текста, то да, не пропускает, считает пустым комментарием. Это старое поведение, не связанное именно с гиф картинками. Могу поменять если нужно 2.Да, скорее всего кеш был виноват, в том что при посте коммента не появилась кнопочка Play на гиф картинке, если теперь стабильно появляеться, значит прогрузился уже свежий джавасктипт

**Comment by Loquinha** [comment]
спасибо, проверила на проде, работает
![image](https://github.com/intersystems-community/developer-community/assets/113416329/2211168b-92e3-4b55-a8ea-f703222bbe6a)
