### ISSUE TITLE
ES DC - Translations on the "Suscriptions" page

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#858]
Hi,

On the Subscription page, most of the translations are not clear, because they are just direct translations and are hard to understand. So just wondering if you could change the translation of these phrases? I want to change more things, but want to see how these changes look before proceeding.

* "Interacciones con tus publicaciones y menciones de tu nombre" instead of "Interacción con las publicaciones y menciones de su perfil"
* "Recibir notificaciones cuando alguien te mencione o te responda." instead of "Reciba notificaciones cuando alguien mencione su perfil o le responda."
* "Recibir notificaciones sobre las personas, etiquetas y publicaciones que sigues." instead of "Reciba notificaciones sobre miembros, etiquetas y publicaciones que sigue.
* "Suscribirse automáticamente a una publicación a la que hayas añadido un comentario." instead of "Suscríbase automáticamente a una publicación a la que haya añadido un comentario."
* "Encuentra miembros a los que seguir." instead of "Encuentra miembros a quién seguir."
* "Recibir notificaciones cuando se añadan publicaciones nuevas en la Comunidad de Desarrolladores en español." instead of "Reciba notificaciones cuando en la Comunidad de desarrolladores se añadan publicaciones nuevas."
* "Recibir notificaciones cuando se añada una respuesta a una publicación en la Comunidad de Desarrolladores en español." instead of "Reciba notificaciones cuando se añada alguna respuesta a una publicación en la Comunidad de desarrolladores.
* "Newsletters (Boletines)" instead of "Boletines"
* "La semana de un vistazo" instead of "La semana en un vistazo"
* "Recibir una recopilación semanal de los artículos, anuncios, preguntas y debates publicados cada semana." instead of "Siga al tanto de las novedades con una compilación semanal de artículos, anuncios, preguntas y debates."
* "Recibir una recopilación mensual de artículos, anuncios, preguntas y debates publicados cada mes, incluyendo las publicaciones más vistas y los autores más populares." instead of "Conozca las novedades de la Comunidad de desarrolladores de forma mensual, incluida la información sobre los artículos y los autores principales del mes."
* "Preguntas y respuestas del mes" instead of "Preguntas y respuestas mensuales"
* "Recibir una recopilación mensual de las preguntas publicadas cada mes." instead of "Reciba una compilación de las preguntas más interesantes del mes y las que aún no tienen respuesta."
* "El año de un vistazo" instead of "Año de un vistazo"
* "Recibir recopilaciones anuales con los mejores artículos, las mejores preguntas y los mejores autores de la Comunidad de Desarrolladores en español; y con las mejores aplicaciones y los mejores desarrolladores de Open Exchange." instead of "Conozca las noticias del año, incluidos los principales artículos e información sobre los principales autores del año de la Comunidad de desarrolladores, los principales desarrolladores y aplicaciones de Open Exchange, y las preguntas más debatidas y populares."

Thanks!
Esther

**Comment by voleynik2** [comment]
@Lena-Ev @CM-DC-ES @Loquinha  complete (at product server)

**Comment by Loquinha** [comment]
hello, all, thank you 
all the stated phrases have been replaced on the product server
![image](https://github.com/intersystems-community/developer-community/assets/113416329/5aa0c391-eca2-4f07-95ad-c1b88e9c70d4)
![image](https://github.com/intersystems-community/developer-community/assets/113416329/13074ca5-a5d2-44ac-9cc3-87fb038738c2)

**Comment by CM-DC-ES** [comment]
Cool, thank you!!
