### ISSUE TITLE
ES DC - New translations for the "Subscription" page

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#859]
Hi,
More phrases to be changed on the Subscription page:

* "Recibirás una notificación cuando alguien comente tu publicación o tu comentario, o te mencione en algún lugar." instead of "Recibirá una notificación cuando alguien comente su publicación o comentario, o mencione su perfil en algún lugar."
* "Recibirás una notificación cuando un miembro que sigues añada una nueva publicación, cuando una publicación que sigues tenga un comentario o cuando en una nueva publicación se incluya una etiqueta que sigues." instead of "Recibirá notificaciones cuando un miembro que usted sigue añada una nueva publicación, cuando en una nueva publicación se incluya una etiqueta que usted sigue o cuando una publicación que sigue tenga una nueva respuesta."
* "Recibirás una notificación cuando alguien añada una publicación en la Comunidad de Desarrolladores." instead of "Recibirá una notificación cuando alguien añada una publicación en la Comunidad de desarrolladores."
* "Recibirás una notificación cuando alguien añada un comentario a cualquier publicación de la Comunidad de Desarrolladores." instead of "Recibirá una notificación cuando alguien añada una respuesta a cualquier publicación de la Comunidad de desarrolladores."
* "No recibirás ningún tipo de notificación de la Comunidad de Desarrolladores (ni correos electrónicos ni notificaciones en la propia Comunidad)." instead of "No recibirá ningún tipo de notificación (correos electrónicos ni notificaciones del sitio web) de la Comunidad de desarrolladores."
* "La configuración de los mensajes directos está bloqueada hasta que publiques algo (un comentario, pregunta, artículo...) en la Comunidad." instead of "Escriba su primer mensaje válido para desbloquear la configuración de los mensajes directos."
* "Ajusta la configuración de los Mensajes Directos." instead of "Prepare su configuración de Mensajes directos."

Thank you!
Esther

**Comment by lelikone** [comment]
Hi Esther!
I changed all the phrases, hopefully it will be correct now.

**Comment by CM-DC-ES** [comment]
Thank you! And a few more:

* "Modo resumen para las suscripciones por correo electrónico" instead of "Modo de resumen para suscripciones de correo electrónico"
* "Todas las notificaciones llegarán por email con la periodicidad seleccionada. Ten en cuenta que, al activar el modo resumen, no recibirás notificaciones de forma inmediata cuando pase algo en la Comunidad." instead of "Todas las notificaciones llegarán por correo electrónico con la periodicidad seleccionada. Tenga en cuenta que, al activar el modo resumen, no recibirá notificaciones de forma inmediata al producirse algún evento."
* "Elige el modo resumen para minimizar el número de emails que recibes de la Comunidad de Desarrolladores." instead of "Cambie al modo de resumen para minimizar el número de correos electrónicos que recibe de la Comunidad de desarrolladores."
* "No recibirás ningún tipo de notificación." instead of "No recibirá ningún tipo de notificación."

Thanks!
Esther

**Comment by lelikone** [comment]
Hi Esther!
I changed all the phrases

**Comment by CM-DC-ES** [comment]
Cool! Thank you!!
