### ISSUE TITLE
Unable to send e-mail. Contact the site administrator if the problem persists.

### ISSUE THREAD

**Issue by daimor** [intersystems-community/developer-community#86]
Some time, after approve answer, I can see such error.
<img width="1165" alt="screenshot 2018-11-08 at 22 46 14" src="https://user-images.githubusercontent.com/1212251/48223490-3d76b200-e3a8-11e8-821b-86aec5ff037e.png">

**Comment by lelikone** [comment]
@daimor Now this problem is?

**Comment by daimor** [comment]
Periodically, saw it.
I'll check if it still happens.

**Comment by daimor** [comment]
Just got the same message, after approving the answer
https://community.intersystems.com/post/iterating-ensrequest-create-json#answer-459686

**Comment by evshvarov** [comment]
@daimor was this fixed? Close please?
