### ISSUE TITLE
Can no longer publish a new release op Intersystems-Monitoring

### ISSUE THREAD

**Issue by isc-tstolker** [intersystems-community/developer-community#860]
Hi,

I can no longer update open exchange applications that I published and I urgently need a new version of Intersystems-Monitoring.

A couple of days back I pressed "Login with Google" by mistake, and no I no longer have the option to Login to OpenExchange.
(Not sure if it is related)

My employee email is theo.stolker@intersystems.com
My Google account is tstolker@gmail.com

Can you please help me out ASAP?

**Comment by Lena-Ev** [comment]
Hi Theo!

Could you please try to log in to open exchange from incognito mode of your
browser.
But in and case you should be able to login both gmail and work account,
but those will be different accounts obviously.
Currently your work account has all the apps on OEx

**Comment by isc-tstolker** [comment]
Hi @Lena-Ev, I have tried that, even tried a different browser, but I can never seem to login properly in OpenExchange.
Is there a known issue with the login button on OpenExchange page not working?

**Comment by isc-tstolker** [comment]
This turned out to be an gegeral issue with Login, and it has been fixed. Thanks, @Lena-Ev
