### ISSUE TITLE
A post's date should be when published

### ISSUE THREAD

**Issue by isc-rsingh** [intersystems-community/developer-community#861]
#### Describe the problem you're observing:
I started a draft post on May 9 and finished it on June 5. When I finally published the post, it was dated May 9. I expected it to be dated June 5, when the post was first made public. 

#### Steps to reproduce, if exist:
Write a draft. Schedule it to be posted on a future date.

**Comment by Lena-Ev** [comment]
Hi Raj, as we can see, you first published post and then put it back in draft. In this scenario we keep the original date. 
We will change your post date for 5 june manually.
