### ISSUE TITLE
Unapproved Browser Push Notifications

### ISSUE THREAD

**Issue by SeanConnelly** [intersystems-community/developer-community#87]
Unapproved posts are triggering push notifications to windows too early. These notifications allow the post to be accessed by non moderators before they are approved.

Suggestions:

1. Push notifications should be disabled for non approved posts to non moderators.
2. Push notifications should be sent when a post is approved.
3. Moderators should probably still receive push notifications of non approved posts. Suggest notification title change from "New Post in Developer Community" to "Unapproved Post in Developer Community".

**Comment by evshvarov** [comment]
1-2 is OK, 3 is not doable ta the moment

**Comment by evshvarov** [comment]
Done
