### ISSUE TITLE
Remove ability to choose fonts in text editor

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/developer-community#89]
Let's leave one default font for the editor. No Comic Sans, etc

**Comment by eduard93** [comment]
https://stackoverflow.com/questions/23538462/how-to-remove-buttons-from-ckeditor-4

**Comment by rcemper** [comment]
A minimum choice of fonts must be kept.
eg. Courier, Arial for Proportional/Fixed size. 
Especially for code text proportional code is almost unreadable. 
At this point addition of &nbr; wou.ld make sense for cote types:
most browser swallow blanks and all COS code without argument (ELSE..) gets broken.
