### ISSUE TITLE
Post counter panel includes deleted comments

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/developer-community#9]
If a mod has deleted a comment on a post, the "# comments" information alongside the post on the homepage counts the deleted comment.

**Comment by daimor** [comment]
the same issue with the answers. In [this post](https://community.intersystems.com/post/pulling-information-credentials-using-cache-object-script)
![image](https://user-images.githubusercontent.com/1212251/36629111-e27b93a0-1951-11e8-9d6f-61d05a90f129.png)
Answers counter shows one answer, but only comments there. 
There are no any unpublished answers to this question. So, I suppose, the answer was deleted.

**Comment by eduard93** [comment]
Still relevant.

[This post](https://community.intersystems.com/post/ensemble-spring-boot-java-app-using-rabbitmq) has 1 comment as of 2019-03-05 11:00:00 GMT+3 

![image](https://user-images.githubusercontent.com/5127457/53789722-2f8c0480-3f36-11e9-8e9b-651d53fe5de2.png)


And it shows 3 comments in counter:

![image](https://user-images.githubusercontent.com/5127457/53789705-200cbb80-3f36-11e9-9798-dd7eb3211ff5.png)

I deleted 2 comments.

**Comment by lelikone** [comment]
bug fixed

**Comment by evshvarov** [comment]
@gjsjohnmurray , could you close it, please?

**Comment by gjsjohnmurray** [comment]
OK, done
