### ISSUE TITLE
Highlight ObjectScript is Munging Code

### ISSUE THREAD

**Issue by SeanConnelly** [intersystems-community/developer-community#90]
Highlight ObjectScript button does not work well with code that contains HTML or XML.

Example...

`write !,"<div>Hello, World!</div>"`

If I paste this into a highlighted ObjectScript block then the block vanishes.

If I highlight the code and select highlight ObjectScript, then the code gets munged.

**Comment by evshvarov** [comment]
Hi @SeanConnelly ! Could you please check if the  issue is solved?

**Comment by evshvarov** [comment]
@SeanConnelly , could you please close it if it's solved?

**Comment by evshvarov** [comment]
@SeanConnelly ? is it fixed?
