### ISSUE TITLE
My Account Links not working

### ISSUE THREAD

**Issue by Noggin79s** [intersystems-community/developer-community#91]
When I go to "My Account" and click Posts to review previous posts I am getting the following error

_The website that you're trying to reach is having technical difficulties and is currently unavailable.
 
We are aware of the issue and are working hard to fix it. Thank you for your patience.__
![capture](https://user-images.githubusercontent.com/29753377/48418876-72766200-e724-11e8-9e05-05018c3264be.PNG)

**Comment by lelikone** [comment]
And now?

**Comment by evshvarov** [comment]
@Noggin79s Could we close it?

**Comment by Noggin79s** [comment]
Yes.
